### DISCUSSION TITLE
Debugging an Nx typescript app running in a Kind cluster in VS Code

### DISCUSSION THREAD

**Discussion by BeyondEvil** [nrwl/nx#10351] [Show and Tell]
We have our Typescript backend applications running in local Kubernetes clusters using [Kind](https://kind.sigs.k8s.io/).

Using VS Code you can attach to the running app (started with `nx serve`) to do live debugging.

Very specific, lol. But if it can help one poor soul, I'll be happy. 😊 

Relevant parts of configurations below.

`kind.yaml`

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
  - role: control-plane
    image: kindest/node:v1.22.7
    extraMounts:
      - hostPath: ./
        containerPath: /project

    extraPortMappings:
      - containerPort: 30180 # myapp http
        hostPort: 10180
      - containerPort: 30129 # myapp debugger
        hostPort: 10129
        protocol: TCP
```

The `extraMounts` is what maps/mounts the local src files into the container running in the Pod.

The `extraPortMappings` is what maps a local port to the `nodePort` (`containerPort`) of the Service attached to the Pod.

`project.json`

``` json
"targets": {
    "serve": {
      "executor": "@nrwl/node:execute",
      "options": {
        "buildTarget": "myapp:build",
        "host": "0.0.0.0"
      }
    },
  }
```

`Service.yaml`

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    name: myapp
  name: myapp
  namespace: services
spec:
  ports:
  - name: http
    nodePort: 30180
    port: 8080
    targetPort: 8080
  - name: debugger
    nodePort: 30129
    port: 9229
    targetPort: 9229
  selector:
    name: notifications-api
  type: NodePort
```

`launch.json` (The VS Code debugger configuration)

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "MyApp Debug",
      "skipFiles":[
        "node_modules/**/*.min.js"
      ],
      "port": 10129,
      "localRoot": "${workspaceFolder}/",
      "remoteRoot": "/project/"
    }
  ]
}
```
