### DISCUSSION TITLE
Can someone help me deal with bitbucket and build:affected

### DISCUSSION THREAD

**Discussion by mattiLeBlanc** [nrwl/nx#23210] [General]
Hi,

I started using build:Affected in my bitbucket pipeline to cut down on build and deployment time to AWS, but I am getting this error in bitbucket:
```
+ pnpm run build:affected
> @apollo/source@0.0.0 build:affected /opt/atlassian/pipelines/agent/build
> nx affected --target build --base=origin/master~1
fatal: ambiguous argument 'origin/master~1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
nx affected
```

I am pretty new to NX and I am not sure why this is happening.
I assume something with NX not having any git history in the container running the deployment.
So is it actually possible to achieve build and deploy affected?

My deploy command looks like:
```
 - step: &deploy
        name: build
        size: 2x #doubling memory size
        image: node:18.14.2
        caches:
          - node
        script:
          - echo "deploy to $ENV"
          - npm install -g pnpm
          - pnpm install
          - pnpm run aws-config
          - pnpm run reset
          # - pnpm run build
          - pnpm run build:affected
          - pnpm run bootstrap
          - pnpm run deploy:affected
          # - pnpm run deploy
          - pnpm run migrate
        artifacts:
          - cdk.out/**
```

One thing that is causing the issue I think is that I deploy based on a tag to trigger the deployment to staging and production:
```
  tags:
    '*':
      - step:
          name: None
          script:
            - npm version
      - step:
          <<: *deploy
          name: Deploy to "staging"
          deployment: staging
          trigger: manual
      - step:
          <<: *deploy
          name: Deploy to "production"
          deployment: production
          trigger: manual

```
Because I saw that the Master deployment  (going to Development) was working as expected.
Just the tag deployment  is failing:
<img width="1194" alt="image" src="https://github.com/nrwl/nx/assets/5285035/79cce076-38f6-4cd6-a03f-3d83d1c932dc">

I just found this in my npm package file, setup by my coworker who is no longer working for us
```
    "build:affected": "nx affected --target build --base=origin/master~1",
    "deploy:affected": "nx affected --target deploy --base=origin/master~1",
```
I am not sure why he is using master~1 because that doesn't work for tags, but works for a master deployment.

When I Look at the master deployment via bitbucket, I see this in the first step:
```
+ umask 000
+ GIT_LFS_SKIP_SMUDGE=1 retry 6 git clone --branch="master" --depth 50 https://x-token-auth:$REPOSITORY_OAUTH_ACCESS_TOKEN@bitbucket.org/$BITBUCKET_REPO_FULL_NAME.git $BUILD_DIR
Cloning into '/opt/atlassian/pipelines/agent/build'...
+ git reset --hard 88f3715496a3f94d80315e8bddfc6b64cab6dbda
HEAD is now at 88f3715 update deployment strategy
+ git config [user.name](http://user.name/) bitbucket-pipelines
+ git config user.email commits-noreply@bitbucket.org
+ git config push.default current
+ git config http.${BITBUCKET_GIT_HTTP_ORIGIN}.proxy http://localhost:29418/
+ git remote set-url origin http://bitbucket.org/$BITBUCKET_REPO_FULL_NAME
+ git reflog expire --expire=all --all
+ echo ".bitbucket/pipelines/generated" >> .git/info/exclude
+ chmod 777 $BUILD_DIR`
```
which is a tagged commit, but this will use the master step for the pipeline:
```
 branches:
    master:
      - step:
          <<: *deploy
          deployment: development
          name: Build and deploy to development
```
and that works fine but when I use the tag deployment bit it fails with the error I mentioned at the beginning.
```
+ umask 000
+ GIT_LFS_SKIP_SMUDGE=1 retry 6 git clone --branch="v0.6.1" --depth 50 https://x-token-auth:$REPOSITORY_OAUTH_ACCESS_TOKEN@bitbucket.org/$BITBUCKET_REPO_FULL_NAME.git $BUILD_DIR
Cloning into '/opt/atlassian/pipelines/agent/build'...
Note: switching to '88f3715496a3f94d80315e8bddfc6b64cab6dbda'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:
  git switch -c <new-branch-name>
Or undo this operation with:
  git switch -

```
I am then running in detached head state....which makes sense because a tag is pointing to a commmit.
Does it mean I have to use a release branch with a tag?
