### DISCUSSION TITLE
Nx should help provide some debug configs or a guide for VSCode

### DISCUSSION THREAD

**Discussion by Playjasb2** [nrwl/nx#23270] [Feature Requests]
## Description

Nx should provide some debug configs for VSCode. More specifically, when we have apps in this monorepo like NestJS, Nx should provide us a launch.json file that would set up the debugger in VSCode such that we can easily attach to our app and be able to debug it step-by-step, without getting any issues with breakpoint bindings.

## Motivation

I tried to debug my NestJS app in my Nx monorepo. I searched online to find the right launch.json config needed for my setup. Some provided a config that would launch the app, while others provided a config that would attach to an existing process, which is what I want.

However, when I try to run the debugger with my script, it worked. But when I try to set the breakpoints, it says it won't bind. I am using the default Nx setup with NestJS. Some people online are suggesting that the issue may be with the source maps. Again I'm not sure.

I am using a setup that involves all my apps being defined in the apps/ directory, and they would bootstrap source code from all my libraries defined in my libs/ directory, that exists at the same level as apps/.

Furthermore, when I try to set this up to debug the app on a Docker container, and have that container expose the debug port, I get issues where I can't connect to it.

Answers online are not very clear here in this regard, and it's taking me hours to try to find some solution. I asked on Discord, but I'm not getting any answers there.

I want to use Nx as my monorepo framework, but I don't want to lose debug capabilities.

## Suggested Implementation

A video or a written guide that explains how to go about debugging apps (including NestJS) in an Nx monorepo in VSCode.

Maybe have Nx create the launch.json for us. Granted, this would be specific to VSCode.

**Comment by surajkrishan** [comment]
UP

**Comment by johnwest80** [comment]
To add to this, i'm not even sure you can debug a nestjs app.  when i serve my app, it gets built in production mode...

```
npx nx serve my-nest-app

> nx run my-nest-app:serve:development

Build option outputFileName not set for my-nest-app. Using fallback value of dist/my-nest-app/main.js.

> nx run my-nest-app:build

> webpack-cli build --node-env=production

chunk (runtime: main) main.js (main) 2.71 KiB [entry] [rendered]

**Reply by vdiaz1130** [reply]
See my comment about the webpack config and running a debug terminal in VS Code 👇

**Comment by FrozenPandaz** [comment]
I've converted this to a discussion to continue discussing what kind of particular configs people would like to see added.

**Comment by vdiaz1130** [comment]
To debug in VS Code, you can open a JavaScript Debug Terminal and start the NestJS App. This works for me with this old `webpack.config`

```
const { composePlugins, withNx } = require('@nx/webpack');
const path = require('path');

module.exports = composePlugins(
  withNx({
    target: 'node',
  }),
  (config) => {
    config.output.devtoolModuleFilenameTemplate = function (info) {
      const rel = path.relative(process.cwd(), info.absoluteResourcePath);
      return `webpack:///./${rel}`;
    };
    return config;
  }
);
```

For some reason, the newer version breaks debugging in VS Code.

I am interested, however, in debugging a Dockerized set of Microservices - from launch (meaning, I would want to add breakpoints in the bootstrap process and not have to first launch the app with `docker compose up` followed by starting the debug console in VS Code). The launch.json in VS Code would require you to configure a debug port for each service (which is cumbersome):

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "address": "0.0.0.0",
      "localRoot": "${workspaceFolder}/apps/reservations-gateway",
      "name": "Debug Reservations Gateway",
      "port": 9229,
      "remoteRoot": "/usr/src/app/apps/reservations-gateway",
      "request": "attach",
      "restart": true,
      "skipFiles": ["<node_internals>/**"],
      "type": "node"
    },
    {
      "address": "0.0.0.0",
      "localRoot": "${workspaceFolder}/apps/auth",
      "name": "Debug Auth Gateway",
      "port": 9230,
      "remoteRoot": "/usr/src/app/apps/auth",
      "request": "attach",
      "restart": true,
      "skipFiles": ["<node_internals>/**"],
      "type": "node"
    }
  ]
}
```

Then you would start the services with docker compose up, then start each debugging service.

Although this is not ideal, **this set up did NOT work for me.**

Here's a sample docker-compose.yml
```
services:
  reservations-gateway:
    build:
      context: .
      platforms:
        - linux/arm64
      dockerfile: ./Dockerfile
      target: development
      args:
        service: reservations-gateway
    command: pnpm nx serve reservations-gateway
    env_file:
      - ./apps/reservations-gateway/.env
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ./apps/reservations-gateway:/usr/src/app/apps/reservations-gateway
      - ./libs:/usr/src/app/libs
  auth:
    build:
      context: .
      platforms:
        - linux/arm64
      dockerfile: ./Dockerfile
      target: development
      args:
        service: auth
    command: pnpm nx serve auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
      - '9230:9230'
    volumes:
      - ./apps/auth:/usr/src/app/apps/auth
      - ./libs:/usr/src/app/libs
  mongo:
    image: mongo
```
The most convenient would be to pass a flag when serving the service and debugging should work whether in Docker or local machine.
