### DISCUSSION TITLE
nx cloud - exceeding limits

### DISCUSSION THREAD

**Discussion by RobbyRabbitman** [nrwl/nx#27318] [Questions] [answered]
I try nx cloud with its hobby plan for the first time, looks really nice!

I wonder what happens when the limits are exceeded?

Will `pnpx nx-cloud start-ci-run --distribute-on='4 linux-medium-js' --stop-agents-after='e2e-vite-version-matrix'` return a non 0 exit code? If yes, Im thinking of just making this step optional, the pipeline would be executed by github actions as is.
If no, what happens? Is the pipeline is executed by github actions as is and nx is not executing the tasks in its cloud? Is there any documentation regarding this case?

If its one of these behaviors nx clouds hobby plan is a nice boost at the start of the month for your ci 😃 

Anyways, thanks for this nice feature and the free hobby plan! The developer experience by just including one line is really, really incredible!

My pipeline looks like this
```yml
name: ci

on:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - run: pnpx nx-cloud start-ci-run --distribute-on='4 linux-medium-js' --stop-agents-after='e2e-vite-version-matrix'

      - uses: nrwl/nx-set-shas@v4

      - run: pnpm i

      - run: pnpm nx report

      - run: pnpm nx run tools-commitlint:exec:message --value "${{ github.event.pull_request.title }}"
        env:
          NX_CLOUD_DISTRIBUTED_EXECUTION: false

      - run: |
          pnpm nx format:check
          pnpm nx affected -t lint-eslint test test-vite build e2e-vite-version-matrix --configuration ci
        env:
          NX_VERBOSE_LOGGING: ${{ runner.debug && true || false }}
```
