### DISCUSSION TITLE
Generator Nx21 + Workspace + Project References

### DISCUSSION THREAD

**Discussion by SombreroElGringo** [nrwl/nx#31266] [Questions] [answered]
Hello everyone,

I am currently migrating one of our legacy NX Monorepos (v16) to a new clean NX 21 Monorepo setup, with the latest workspace and references configuration.

While experimenting with the provided generators, I’ve noticed that each time I generate a publishable library, it automatically adds the following entry to my `yarn.lock`:

```
"@org/mytslib@workspace:libs/mytslib":
  version: 0.0.0-use.local
  resolution: "@org/mytslib@workspace:libs/mytslib"
  dependencies:
    tslib: "npm:^2.3.0"
  languageName: unknown
  linkType: soft
```

My question is: Does @nx/devkit provide any utilities or best practices for managing this new workspace resolution format in yarn.lock when generating sharable libraries from custom generators? Alternatively, does anyone have an example of how to handle this in the recommended NX way?

Any guidance would be greatly appreciated! 🙏
