### DISCUSSION TITLE
Question regarding Github Actions - `nx not found`

### DISCUSSION THREAD

**Discussion by thezeronine** [nrwl/nx#5157] [General]
Hey there,

I'm kinda struggling with setting up a Github Actions workflow for my nx repo. I always get an "nx not found" in the jobs `build`, `lint` and `test`. Any ideas? It works when everything is just one job.

```yaml
name: frontend workflow

on:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.16.0]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-node-modules-cache-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch --no-tags --prune --depth=5 origin main
      - name: install dependencies
        if: steps.cache-node-modules.cache-hit != 'true'
        run: yarn install --frozen-lockfile

  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-node-modules-cache-${{ hashFiles('**/yarn.lock') }}
      - name: build affected
        run: nx run affected:build --base=origin/main

  lint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-node-modules-cache-${{ hashFiles('**/yarn.lock') }}
      - name: lint affected
        run: nx run affected:lint --base=origin/main

  test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-node-modules-cache-${{ hashFiles('**/yarn.lock') }}
      - name: unit test affected
        run: nx run affected:test --base=origin/main

```

Error:
```
Run nx run affected:build --base=origin/main
  nx run affected:build --base=origin/main
  shell: /usr/bin/bash -e {0}
/home/runner/work/_temp/baf783f1-dab3-413b-9ff2-dcb8a61ca524.sh: line 1: nx: command not found
Error: Process completed with exit code 127.
```
