### DISCUSSION TITLE
Can someone validate azure pipeline yml for nx affected building in Azure DevOps? First timer.

### DISCUSSION THREAD

**Discussion by MichalLechowski** [nrwl/nx#7592] [General]
Hi everyone,

I've been trying to configure Angular project based on NX to build properly in Azure Pipelines. Both for PR and CI purposes. I got it working but I am not sure if it's correct. The examples and the docs are too entry-level and I feel lack of proper documentation for real-life scenarios.

The idea is pretty default: use only affected build for incoming pull requests, validate PR build to allow completing PR and then trigger CI build on main branch.

My configuration atm is as follows:
```
jobs:

  - job: ci //this is triggered for integration build, on push to main
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    condition: ne(variables['Build.Reason'], 'PullRequest')
    steps:
      - template: .azure-pipelines/steps/install-node-modules.yml
      - script: npx nx affected myAppName --target=build --base=origin/main~1 --parallel
        workingDirectory: myDir
        displayName: NX affected
    
      - task: ArchiveFiles@2
        displayName: 'Zip Angular Bundle'
        inputs:
          rootFolderOrFile: myDir/dist/apps/myAppName
          includeRootFolder: false
          archiveFile: 'angular_bundles.zip'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        inputs:
          PathtoPublish: 'angular_bundles.zip'


  - job: pr //triggered for PR build (build policy)
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    steps:
      - template: .azure-pipelines/steps/install-node-modules.yml
      - script: npx nx affected myAppName --target=build --base=origin/main --parallel
        workingDirectory: myDir
        displayName: NX affected
```

**My concerns are mostly** --base parameters. Are they all right? It works, when I change something in X library then the pipeline log triggers affected build for only that part of angular project. But I am not sure if that's how it should be.
I don't know if I fully understand the affected process. As I see it:
1) refer current head of main in PR build to check for differences between current main vs incoming branch PR
2) in CI build since the PR is already there and completed, the build should refer to one commit deeper to skip the last PR squash commit? Not sure.

The template to install-node-modules.yml, if you need take a look, too:
```
steps:
- task: Cache@2
  displayName: 'Cache npm Dependencies'
  inputs:
    key: '**/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json'
    path: '$(Build.SourcesDirectory)/myDir/node_modules'
    cacheHitVar: CacheRestored

- task: Npm@1
  displayName: 'npm ci'
  inputs:
    verbose: false
- script: | 
    npm --prefix "$(System.DefaultWorkingDirectory)/myDir" ci 
  condition: eq(variables['CacheRestored'],False)
```

It's only conditional caching of nugets.
