### DISCUSSION TITLE
How to use Nx with Chroma UI?

### DISCUSSION THREAD

**Discussion by mrlubos** [nrwl/nx#9229] [General]
In my non-monorepo project, I use Chroma UI Github action to publish Storybook to Chromatic. What's the best way to migrate this script to Nx?

```yml
uses: chromaui/action@v1
  with:
    buildScriptName: storybook-build
    exitOnceUploaded: true
    exitZeroOnChanges: true
    projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    token: ${{ secrets.GITHUB_TOKEN }}
```
