### DISCUSSION TITLE
How to define variables in library from helm chart environment variables

### DISCUSSION THREAD

**Discussion by siddtheone** [nrwl/nx#9593] [General]
Suppose I have some variables in helm charts
```yml
-env:
    CLIENTID: 1234567890,
    NX_CLIENTID: 12344567890
```
How can I use these environment variables to initialize JS variables in an NX library?

```js
{
  CLIENTID: process.env.CLIENTID || process.env.NX_CLIENTID
}
```

However above approach not worked for me?
