### ISSUE TITLE
Add Gitlab CI Example with yarn

### ISSUE THREAD

**Issue by simpros** [nrwl/nx#10057]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

I am talking about [this](https://nx.dev/ci/monorepo-ci-gitlab) page.

I am using yarn as package manager (as in most parts of your documentation). But this CI example only makes use of npm. I tried to adapt the commands to yarn, but that just does not work at all.
In general a clear line between npm and yarn should be chosen, because some tutorials/guides use npm and others use yarn.

**Comment by bcabanes** [comment]
Hi @simpros!
I understand your your issue but this should be pretty straight forward to do, replacing `npx` with `yarn` from what is currently shown. 
The cache step would need to be updated according to [GitLab's documentation](https://docs.gitlab.com/ee/ci/caching/#compute-the-cache-key-from-the-lock-file) and could look like the following:
```yml
cache:
    key:
      files:
        - yarn.lock
    paths:
      - '.yarn-cache/'
  script:
    - yarn install --cache-folder .yarn-cache --prefer-offline --frozen-lockfile
```

Additionally, the second example showing the Nx Cloud setup is using Yarn already.

Thank you for your support!
