### ISSUE TITLE
GitLab CI example doesn't work

### ISSUE THREAD

**Issue by bazter** [nrwl/nx#10089]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[GitLab CI documentation page](https://nx.dev/ci/monorepo-ci-gitlab#configuring-ci-using-gitlab-and-nx)

### Additional context or description

For GitLab v14.6.2 I am having an issue, where given example of .gitlab-ci.yml is invalid. Task `install-dependencies` is missing script or trigger property. When I tried to replace `before_script` with `script` it works, but all the tasks from next stage (test) fail:

error example:  
```
$ npx nx workspace-lint
npm WARN exec The following package was not found and will be installed: nx
 >  NX   Could not find Nx modules in this workspace.
   Have you run npm/yarn install?
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 1
```

edit: 

I realised that the jobs from test stage are simply missing the cache property (for example with pull policy). I tried to add it to the shared `.distributed` section.

```
.distributed:
  interruptible: true
  only:
    - main
    - merge_requests
  needs:
    - install-dependencies
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
    policy: pull
  artifacts:
    paths:
      - node_modules/.cache/nx
```

This makes them download and use the cache properly. The last piece I'm missing tho is how to make those jobs work without running `npm install` in each of them. Node modules folder is simply not there, only the `.npm` folder is available (from the cache). What am I missing  here?

Btw the example also uses `nx affected` command, which requires `git` to work. Used docker image `node:16-alpine` doesn't include git and thus the scripts throw an error:
```
/bin/sh: git: not found
```

For now, I fixed that by adding this to the `.distributed` section as well
```
before_script:
    - apk add --update git
```
