### ISSUE TITLE
Configuring CI Using GitLab and Nx

### ISSUE THREAD

**Issue by michalvadak** [nrwl/nx#11337]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/ci/monorepo-ci-gitlab

### Additional context or description

Is this setup for Gitlab CI/CD correct? It starts all of the jobs `workspace-lint`, `format-check`,`lint`, `test`, `build` at the same time and all of them are installing yarn. It seems kinda unoptimized but I am no expert. Also I am not using Nx Cloud to be clear. Can somebody explain to me the reason for this implementation or suggest a better one?

**Comment by AgentEnder** [comment]
We do this for a few reasons. 
- In a large workspace, installing packages typically takes less time than executing tests, linting, or building do individually
- Starting the jobs at the same time allows them to execute in parallel
- The setup allows for an easy transition to DTE.

**Comment by michalvadak** [comment]
This setup takes approximately 6 minutes 20 seconds
```
image: node:16
stages:
  - setup
  - test
  - build

install-dependencies:
  stage: setup
  interruptible: true
  only:
    - main
    - testing
    - merge_requests
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
      - .yarn
  script:
    - yarn install --pure-lockfile --cache-folder .yarn --prefer-offline
  artifacts:
    paths:
      - node_modules

.distributed:
  interruptible: true
  only:
    - main
    - testing
    - merge_requests
  needs:
    - install-dependencies
  before_script:
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}
  artifacts:
    paths:
      - node_modules/.cache/nx

workspace-lint:
  stage: test
  extends: .distributed
  script:
    - yarn nx workspace-lint --base=$NX_BASE --head=$NX_HEAD

format-check:
  stage: test
  extends: .distributed
  script:
    - yarn nx format:check --base=$NX_BASE --head=$NX_HEAD

lint:
  stage: test
  extends: .distributed
  script:
    - yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=3

test:
  stage: test
  extends: .distributed
  script:
    - yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=test --parallel=3 --ci --code-coverage

build:
  stage: build
  extends: .distributed
  script:
    - yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3
```


And this one from your page takes approximately 11 minutes
```
image: node:16
stages:
  - test
  - build

.distributed:
  interruptible: true
  only:
    - main
    - testing
    - merge_requests
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn/
  before_script:
    - yarn install --pure-lockfile --cache-folder .yarn --prefer-offline
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}
  artifacts:
    paths:
      - node_modules/.cache/nx

workspace-lint:
  stage: test
  extends: .distributed
  script:
    - yarn nx workspace-lint --base=$NX_BASE --head=$NX_HEAD

format-check:
  stage: test
  extends: .distributed
  script:
    - yarn nx format:check --base=$NX_BASE --head=$NX_HEAD

lint:
  stage: test
  extends: .distributed
  script:
    - yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=3

test:
  stage: test
  extends: .distributed
  script:
    - yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=test --parallel=3 --ci --code-coverage

build:
  stage: build
  extends: .distributed
  script:
    - yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3
```
