### ISSUE TITLE
Move some dependencies to peerDependencies

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#11664]
When dependency is not strict, please consider moving it to peerDependencies (when possible).

## Description
Let's take as an example of `@nrwl/angular` (although the scope is not `angular` for this feature).
It has list of dependencies:
```
  dependencies:
    "@angular-devkit/schematics" "~14.1.1"
    "@nrwl/cypress" "14.5.8"
    "@nrwl/devkit" "14.5.8"
    "@nrwl/jest" "14.5.8"
    "@nrwl/linter" "14.5.8"
    "@nrwl/storybook" "14.5.8"
    "@nrwl/web" "14.5.8"
    "@nrwl/workspace" "14.5.8"
    "@phenomnomnominal/tsquery" "4.1.1"
    "@schematics/angular" "~14.1.0"
    chalk "4.1.0"
    chokidar "^3.5.1"
    http-server "^14.1.0"
    ignore "^5.0.4"
    jasmine-marbles "~0.8.4"
    magic-string "~0.26.2"
    minimatch "3.0.5"
    semver "7.3.4"
    ts-node "10.9.1"
    tsconfig-paths "^3.9.0"
    tslib "^2.3.0"
    webpack "^5.58.1"
    webpack-merge "5.7.3"
```

Even if we don't use Cypress for e2e (if you like Playwright more), or Jest, or Storybook, these dependencies will be installed anyway. It's not a critical issue, of course, but I think Nx can add them during the workspace creation as devDependencies to package.json if user selects Cypress or some other tool during the process (and I think it already happens), so these dependencies will be added anyway.

## Motivation
Some sub-dependencies can be quite heavy and take some time to install. Implementation of this feature would decrease "yarn install" step time for every CI build.

**Comment by harvestnide** [comment]
Also, yarn berry is not happy with unmet peer dependencies (yeah I know that it's not properly supported by nx yet). I'm trying to maintain [peer resolutions](https://yarnpkg.com/configuration/yarnrc#packageExtensions) in my `.yarnrc`, but it's messy 

Example:
```yaml
#.yarnrc.yml
packageExtensions:
  "@nrwl/cli@14.5.4":
    peerDependencies:
      "@nrwl/js": 14.5.4
  "@nrwl/cypress@14.5.4":
    peerDependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
      "@nrwl/js": 14.5.4
      babel-loader: "*"
      nx: 14.5.4
      typescript: "*"
      webpack: "*"
  "@nrwl/eslint-plugin-nx@14.5.4":
    peerDependencies:
      "@nrwl/js": 14.5.4
      eslint: "*"
      nx: 14.5.4
      typescript: "*"
  "@nrwl/jest@14.5.4":
    peerDependencies:
      nx: 14.5.4
  "@nrwl/js@14.5.4":
    peerDependencies:
      nx: 14.5.4
      typescript: "*"
  "@nrwl/linter@14.5.4":
    peerDependencies:
      nx: 14.5.4
      typescript: "*"
  "@nrwl/next@14.5.4":
    peerDependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
      "@nrwl/js": 14.5.4
      "@types/node": "*"
      babel-loader: "*"
      eslint: "*"
      nx: 14.5.4
      typescript: "*"
      webpack: "*"
```
