### ISSUE TITLE
nx affected:build failing with error: "fatal: No such ref" when running in GitHub actions

### ISSUE THREAD

**Issue by Maoragai12** [nrwl/nx#12203]
## Current Behavior & Failure Logs

The `affected:build` is failing with the error message:
```
fatal: No such ref: '99def6ebd8d05642b7376bf138df9bcc148b70c1'
```

This is my package.json scripts:

```
  "scripts": {
    "prepare": "cd ${pwd} && husky install ${pwd}/.husky",
    "lint": "npx nx lint --verbose",
    "affected:lint": "npx nx affected --target=lint --verbose",
    "test": "npx nx test --verbose",
    "affected:test": "npx nx affected --target=test --verbose",
    "build:dev": "npx nx build --args='--envType=dev' --verbose",
    "build:test": "npx nx build --args='--envType=test' --verbose",
    "build:prod": "npx nx build --args='--envType=prod' --verbose",
    "affected:build:dev": "npx nx affected --target=build --args='--envType=dev' --verbose",
    "affected:build:test": "npx nx affected --target=build --args='--envType=test' --verbose",
    "affected:build:prod": "npx nx affected --target=build --args='--envType=prod' --verbose",
    "deploy:dev": "npx nx deploy --args='--envType=dev' --verbose",
    "deploy:test": "npx nx deploy --args='--envType=test' --verbose",
    "deploy:prod": "npx nx deploy --args='--envType=prod' --verbose",
    "affected:deploy:dev": "npx nx affected --target=deploy --args='--envType=dev' --verbose",
    "affected:deploy:test": "npx nx affected --target=deploy --args='--envType=test' --verbose",
    "affected:deploy:prod": "npx nx affected --target=deploy --args='--envType=prod' --verbose"
  }
```

This is my build step:

```
  build:
    name: Build
    needs: 
      - config
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Pull the full git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sets the base and head SHAs
        uses: nrwl/nx-set-shas@v3

      - name: Restore node modules from cache
        id: node-modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true

      - run: git fetch --all

      - name: Install node modules
        if: ${{ steps.node-modules.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Install SAM
        uses: aws-actions/setup-sam@v1

      - name: Restore repository from cache
        uses: actions/cache@v2
        with:
          path: |
            ./*
            !./node_modules
          key: ${{ github.sha }}-run-${{ needs.config.outputs.run-timestamp }}

      - name: Cache the build directory
        uses: actions/cache@v2
        with:
          path: ./.aws-sam/*
          key: ${{ github.sha }}-build-${{ needs.config.outputs.run-timestamp }}

      - name: Build the Lambda
        shell: bash
        run: npm run affected:build:prod
```

The `nrwl/nx-set-shas@v3` action injects the base and head automatically to the nx script. The build recognize and prints the base and the head SHAs, but can't access to this ref: 

```
Run npm run affected:build:prod

> npx nx affected --target=build --args='--envType=prod' --verbose


 >  NX   No explicit --base argument provided, but found environment variable NX_BASE so using its value as the affected base: [9](https://github.com/Maoragai12/nx-aws-sam/actions/runs/3109948756/jobs/5040657317#step:11:10)9def6ebd8d05642b7376bf138df9bcc148b70c1

 >  NX   No explicit --head argument provided, but found environment variable NX_HEAD so using its value as the affected head: 64f4a17214291cae2062b9d67d630f245000d4ab

fatal: No such ref: '99def6ebd8d05642b7376bf138df9bcc148b70c1'
nx affected

Run target for affected projects

Run command using --base=[SHA1] (affected by the committed, uncommitted and untracked changes):
  --base  Base of the current branch (usually main)  [string]

or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
  --base  Base of the current branch (usually main)  [string]
  --head  Latest commit of the current branch (usually HEAD)  [string]

or using:
  --files        Change the way Nx is calculating the affected command by providing directly changed files, list of files delimited by commas  [array]
  --uncommitted  Uncommitted changes  [boolean]
  --untracked    Untracked changes  [boolean]

Options:
  --help              Show help  [boolean]
  --version           Show version number  [boolean]
  --target            Task to run for affected projects  [string] [required]
  --parallel          Max number of parallel processes [default is 3]  [string]
  --output-style      Defines how Nx emits outputs tasks logs  [string] [choices: "dynamic", "static", "stream", "stream-without-prefixes"]
  --all               All projects  [boolean]
  --exclude           Exclude certain projects from being processed  [array] [default: []]
  --runner            This is the name of the tasks runner configured in nx.json  [string]
  --skip-nx-cache     Rerun the tasks even when the results are available in the cache  [boolean] [default: false]
  --configuration     This is the configuration to use when performing tasks on projects  [string]
  --only-failed       Isolate projects which previously failed  [deprecated: The command to rerun failed projects will appear if projects fail. This now does nothing and will be removed in v15.] [boolean] [default: false]
  --verbose           Prints additional information about the commands (e.g., stack traces)  [boolean] [default: false]
  --nx-bail           Stop command execution after the first failed task  [boolean] [default: false]
  --nx-ignore-cycles  Ignore cycles in the task graph  [boolean] [default: false]

Examples:
  affected --target=custom-target                         Run custom target for all affected projects
  affected --target=test --parallel=5                     Run tests in parallel
  affected --target=test --all                            Run the test target for all projects
  affected --target=test --files=libs/mylib/src/index.ts  Run tests for all the projects affected by changing the index.ts file
  affected --target=test --base=main --head=HEAD          Run tests for all the projects affected by the changes between main and HEAD (e.g., PR)
  affected --target=test --base=main~1 --head=main        Run tests for all the projects affected by the last commit on main

Find more information and examples at https://nx.dev/cli/affected

Error: Command failed: git merge-base --fork-point "99def6ebd8d05642b7376bf138df9bcc148b70c1" "64f4a17214291cae2062b9d67d630f245000d4ab"
fatal: No such ref: '99def6ebd8d05642b7376bf138df9bcc148b70c1'

    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at getFilesUsingBaseAndHead (/home/runner/work/nx-aws-sam/nx-aws-sam/node_modules/nx/src/utils/command-line-utils.js:284:50)
    at parseFiles (/home/runner/work/nx-aws-sam/nx-aws-sam/node_modules/nx/src/utils/command-line-utils.js:253:20)
    at projectsToRun (/home/runner/work/nx-aws-sam/nx-aws-sam/node_modules/nx/src/command-line/affected.js:[10](https://github.com/Maoragai12/nx-aws-sam/actions/runs/3109948756/jobs/5040657317#step:11:11)0:145)
    at Object.<anonymous> (/home/runner/work/nx-aws-sam/nx-aws-sam/node_modules/nx/src/command-line/affected.js:29:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/nx-aws-sam/nx-aws-sam/node_modules/tslib/tslib.js:[11](https://github.com/Maoragai12/nx-aws-sam/actions/runs/3109948756/jobs/5040657317#step:11:12)5:62) {
  status: [12](https://github.com/Maoragai12/nx-aws-sam/actions/runs/3109948756/jobs/5040657317#step:11:13)8,
```

## Expected Behavior
It should build successfully the affected projects.

### Environment
```
   Node : 16.17.0
   OS   : darwin arm64
   npm  : 8.15.0
   
   nx : 14.7.5
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.5
   @nrwl/eslint-plugin-nx : 14.7.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.5
   @nrwl/js : 14.7.5
   @nrwl/linter : 14.7.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.7.5
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.5
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

```

Any ideas?

Thanks!
