### ISSUE TITLE
Github Action CI recipe yields error on test step

### ISSUE THREAD

**Issue by kylebjordahl** [nrwl/nx#13077]
## Current Behavior
When using the CI recipe for Github Actions, the testing step yields the following error message:

`Nx no longer supports using positional arguments for base and head. Please use --base and --head instead.`

The CI command appears to fail because the recipe passes `--ci --code-coverage` and not `--base` or `--head`. 

Appending _either_ `--base` or `--head` solves the problem, as does `--`.

## Expected Behavior
Test step runs without error using the recipe as provided (maybe fixing the recipe/generator is easier, but being forced to pass any of these flags is somewhat unintuitive)

## Steps to Reproduce
run test step command locally in Nx integrated repo:

`npx nx affected --target=test --parallel=3 --ci --code-coverage`

### Failure Logs
```Run npx nx affected --target=test --parallel=3 --ci --code-coverage
  npx nx affected --target=test --parallel=3 --ci --code-coverage
  shell: /usr/bin/bash -e {0}
  env:
    NX_BASE: <REDACTED COMMIT HASH>
    NX_HEAD: <REDACTED COMMIT HASH>

nx affected

Run target for affected projects

Run command using --base=[SHA1] (affected by the committed, uncommitted and untracked changes):
  --base  Base of the current branch (usually main)  [string]

or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
  --base  Base of the current branch (usually main)  [string]
  --head  Latest commit of the current branch (usually HEAD)  [string]

or using:
  --files        Change the way Nx is calculating the affected command by providing directly changed files, list of files delimited by commas  [array]
  --uncommitted  Uncommitted changes  [boolean]
  --untracked    Untracked changes  [boolean]

Options:
  --help              Show help  [boolean]
  --version           Show version number  [boolean]
  --target            Task to run for affected projects  [string] [required]
  --parallel          Max number of parallel processes [default is 3]  [string]
  --output-style      Defines how Nx emits outputs tasks logs  [string] [choices: "dynamic", "static", "stream", "stream-without-prefixes"]
  --all               All projects  [boolean]
  --exclude           Exclude certain projects from being processed  [array] [default: []]
  --runner            This is the name of the tasks runner configured in nx.json  [string]
  --skip-nx-cache     Rerun the tasks even when the results are available in the cache  [boolean] [default: false]
  --configuration     This is the configuration to use when performing tasks on projects  [string]
  --verbose           Prints additional information about the commands (e.g., stack traces)  [boolean] [default: false]
  --nx-bail           Stop command execution after the first failed task  [boolean] [default: false]
  --nx-ignore-cycles  Ignore cycles in the task graph  [boolean] [default: false]

Examples:
  affected --target=custom-target                         Run custom target for all affected projects
  affected --target=test --parallel=5                     Run tests in parallel
  affected --target=test --all                            Run the test target for all projects
  affected --target=test --files=libs/mylib/src/index.ts  Run tests for all the projects affected by changing the index.ts file
  affected --target=test --base=main --head=HEAD          Run tests for all the projects affected by the changes between main and HEAD (e.g., PR)
  affected --target=test --base=main~1 --head=main        Run tests for all the projects affected by the last commit on main

Find more information and examples at https://nx.dev/nx/affected

Nx no longer supports using positional arguments for base and head. Please use --base and --head instead.
```
### Environment
Github Actions CI runner, action config yml:
(note that for unavoidable reasons, our nx worspace resides in a subfolder of the actual repo)

```yml
  monorepo_ci:
    name: Monorepo Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ohm

    concurrency:
      group: monorepo-test-suites-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
        name: Pull repo
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: 16.15
          cache: 'npm'
          cache-dependency-path: ohm/package-lock.json

      - name: Install dependencies
        run: npm ci

      - uses: nrwl/nx-set-shas@v3
        name: Setup Nx base and head

      - run: npx nx workspace-lint
        name: Workspace Linting

      - run: npx nx format:check
        name: Format check

      - run: npx nx affected --target=generate --configuration=check
        name: Generated code check

      - run: npx nx affected --target=lint --parallel=3
        name: Lint affected

      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
        name: Test affected

      - run: npx nx affected --target=build --parallel=3
        name: Build affected
```
