### ISSUE TITLE
nx-cloud is at 15.0.2 (latest), but nx-cloud is throwing an error when using @nrwl/* packages at 15.2.0

### ISSUE THREAD

**Issue by fbartho** [nrwl/nx#13303]
### Current Behavior

In CI we use
```
$ npx nx-cloud stop-all-agents
```
In order to stop agents when CI is cancelled/skipped in a way that the main workflow would miss. This was working fine last week, but then we noticed as of today nx-cloud is throwing the following error:

```
This version of Nx Cloud is incompatible with the @nrwl/* packages in your workspace.

Match your @nrwl/nx-cloud version to the same major version of your @nrwl/* packages and try again.
```

### Expected Behavior

`npx nx-cloud` when using the latest version published shouldn't cause any problems when using the latest version of the core tools.

### Steps to Reproduce

1. Update your workspace to latest 15.2.0 `@nrwl/*` packages
2. Run `npx nx-cloud stop-all-agents`
3. Notice the unexpected error telling you to try again.

### Nx Report

```shell
Node : 18.11.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.2.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.2.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.0
   @nrwl/expo : Not Found
   @nrwl/express : 15.2.0
   @nrwl/jest : 15.2.0
   @nrwl/js : 15.2.0
   @nrwl/linter : 15.2.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.2.0
   @nrwl/nx-cloud : 15.0.2   <--- Notice!!
   @nrwl/nx-plugin : 15.2.0
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.2.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.2.0
   @nrwl/webpack : 15.2.0
   @nrwl/workspace : 15.2.0
   typescript : 4.9.3
   ---------------------------------------
   Local workspace plugins:
         @hca/package-generator
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
2022-11-21T23:50:35.6803133Z ##[group]Run npx nx-cloud stop-all-agents
2022-11-21T23:50:35.6803439Z [36;1mnpx nx-cloud stop-all-agents[0m
2022-11-21T23:50:35.6856819Z shell: /usr/bin/bash -e {0}
2022-11-21T23:50:35.6857034Z env:
2022-11-21T23:50:35.6857388Z   GITHUB_TOKEN: ***
2022-11-21T23:50:35.6857589Z ##[endgroup]
2022-11-21T23:50:36.5611327Z npm WARN exec The following package was not found and will be installed: nx-cloud@15.0.2
2022-11-21T23:50:37.3190435Z NX CLOUD ERROR
2022-11-21T23:50:37.3194595Z ---------------------------------------
2022-11-21T23:50:37.3195317Z This version of Nx Cloud is incompatible with the @nrwl/* packages in your workspace.
2022-11-21T23:50:37.3195829Z 
2022-11-21T23:50:37.3196639Z Match your @nrwl/nx-cloud version to the same major version of your @nrwl/* packages and try again.
```

**Comment by fbartho** [comment]
Note: this doesn't block us, but it does waste 2hrs of our CI time (30mins per Agent) when it would have happened. That's ironic since we're paying for nx-cloud to save us CI minutes.

**Comment by StalkAltan** [comment]
Hi @fbartho!

Can you verify that no other steps in your pipeline are failing? Sometimes this can happen when something goes wrong with your package manager install -- admittedly, we should improve the error messaging.

**Comment by fbartho** [comment]
This codepath uses NPX because I'm not actually doing a full `yarn install` in this situation, here's the full workflow job:

```yaml
  agent-hunter:
    name: NX Cloud Agent Daemon hunter - if CI skipped
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [build]
    if: |
      always() && needs.build.result == 'skipped'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1 # Only checkout the minimum data!
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Get cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Stop Cloud Agents
        run: npx nx-cloud stop-all-agents
```

In the case where our CI build job is skipped (because it was pending, and a dev pushed a new commit, or added a label, for example), then the Agents (which are in a matrix) would still be spun up, but the build-job wouldn't ever stop them. This job stops them.

So this job installs nx-cloud using npx, so there's no node_modules present at this time.
