### ISSUE TITLE
Azure pipeline doesn't fail on failed job

### ISSUE THREAD

**Issue by ysdidenko** [nrwl/nx#13923]
### Current Behavior

Azure pipeline build shows all green even when some step is failing (test, lint, e2e, or any combination) 
<img width="1175" alt="1" src="https://user-images.githubusercontent.com/32298983/208736862-79c9acac-33f0-4c32-892f-d3a17ba8ab84.png">

### Expected Behavior

The Azure pipeline build should fail whenever any of the steps failed.

### Steps to Reproduce

Here is our pipeline YAML
```yml
jobs:
- job: agent
  strategy:
    parallel: 3
  steps:
    - script: yarn --pure-lockfile
      displayName: "Yarn"
    - script: yarn nx-cloud start-agent
      displayName: "Yarn start agents" 
  timeoutInMinutes: 120     
- job: pr
  steps:
    - script: yarn --pure-lockfile
      displayName: "Yarn"
    - script: yarn nx-cloud start-ci-run --stop-agents-on-failure=true
      displayName: "Start-CI-Run"
    - script: npx nx affected --base=origin/master --head=HEAD --target=build --parallel=3 & npx nx affected --base=origin/master --head=HEAD --target=test --parallel=3 & npx nx affected --base=origin/master --head=HEAD --target=lint --parallel=3 & npx nx affected --base=origin/master --head=HEAD --target=e2e --spec=**/e2e/**/ci/**/*  --parallel=2
      displayName: "DTE: Build, Test, Lint, E2E"
```

### Nx Report

```shell
Node : 18.10.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 14.6.5
   @nrwl/angular : 14.6.1
   @nrwl/cypress : 14.6.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.6.1
   @nrwl/eslint-plugin-nx : 14.6.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.6.1
   @nrwl/js : 14.6.1
   @nrwl/linter : 14.6.1
   @nrwl/nest : 14.6.1
   @nrwl/next : Not Found
   @nrwl/node : 14.6.1
   @nrwl/nx-cloud : 14.6.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.6.1
   @nrwl/web : 14.6.1
   @nrwl/workspace : 14.6.1
   typescript : 4.7.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 14.1.0
         @ngrx/effects: 14.1.0
         @ngrx/entity: 14.1.0
         @ngrx/router-store: 14.1.0
         @ngrx/store: 14.1.0
         @ngrx/store-devtools: 14.1.0
         @ngx-pwa/local-storage: 13.0.2
         @nxtend/capacitor: 11.1.1
         apollo-angular: 3.0.1
         ngx-build-plus: 14.0.0
         @ngrx/schematics: 14.0.2
         ngx-build-plus: 14.0.0
```
