### ISSUE TITLE
ci-workflow generator use specified main branch name,maybe better.

### ISSUE THREAD

**Issue by cbl980226** [nrwl/nx#14540]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Motivation

create-nx-workspace
``` bash
npx create-nx-workspace@latest -a
# prompt: Main branch name · master
# prompt: Enable distributed caching to make your CI faster · Yes
# prompt: CI workflow file to generate? · github
```
push origin
```bash
git push -u origin master
```

github action error

## Suggested Implementation

https://github.com/nrwl/nx/blob/c6adec7f9d9536eee9507cdc38a0209af69dce02/packages/workspace/src/generators/ci-workflow/files/github/.github/workflows/__workflowFileName__.yml__tmpl__#L13

```yml
jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.2
    with:
      main-branch-name: <%= mainBranch %>
```
