### ISSUE TITLE
Many nx packages have missing peerDependencies

### ISSUE THREAD

**Issue by MageJohn** [nrwl/nx#14694]
### Current Behavior

Modern Yarn is more strict about dependencies than other package managers, and it highlights issues with peer dependencies in nx packages. These can be worked around with the `packageExtensions` key in the `.yarnrc.yml` file, but it can get messy. For example, here's what I have in the repro repository for this issue:

```yml
packageExtensions:
  "@nrwl/devkit@*":
    peerDependencies:
      typescript: "^3 || ^4"
  "@nrwl/eslint-plugin-nx@*":
    peerDependencies:
      nx: ">= 14 <= 16"
      typescript: "^3 || ^4"
      eslint: "^6.0.0 || ^7.0.0 || ^8.0.0"
  "@nrwl/jest@*":
    peerDependencies:
      nx: ">= 14 <= 16"
      typescript: "^3 || ^4"
  "@nrwl/js@*":
    peerDependencies:
      nx: ">= 14 <= 16"
      typescript: "^3 || ^4"
  "@nrwl/linter@*":
    peerDependencies:
      nx: ">= 14 <= 16"
      typescript: "^3 || ^4"
  "@nrwl/react@*":
    peerDependencies:
      nx: ">= 14 <= 16"
      typescript: "^3 || ^4"
  "@nrwl/workspace@*":
    peerDependencies:
      typescript: "^3 || ^4"

```

Without this, yarn spits out a whole long list of warnings about unmet peer dependencies.

### Expected Behavior

I expect that nx packages to correctly list their peer dependencies; that means not just their own, but also those of dependants that are not met by that package.

### GitHub Repo

https://github.com/MageJohn/repro-nx-peer-dep

### Steps to Reproduce

1. Clone the repo
2. Run `git checkout pre-workaround`. This is the repo state before applying the `packageExtensions` workaround
3. Run `yarn`. This should show 13 `YN0002` warnings complaining about unmet peer dependencies.
4. Run `git checkout main` to go back to the branch tip, where the `packageExtensions` workaround has been applied.
5. Run `yarn` again. There should be no errors or warnings now.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 14.17.1
   OS   : darwin x64
   yarn : 3.3.1
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
$> yarn
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @nrwl/devkit@npm:15.6.3 [651ca] doesn't provide typescript (p18901), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/devkit@npm:15.6.3 [f7a63] doesn't provide typescript (p5710e), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/eslint-plugin-nx@npm:15.6.3 [46a57] doesn't provide eslint (pc6328), requested by @typescript-eslint/utils
➤ YN0002: │ @nrwl/eslint-plugin-nx@npm:15.6.3 [46a57] doesn't provide nx (pee9e3), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/jest@npm:15.6.3 doesn't provide nx (pf0d81), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/jest@npm:15.6.3 doesn't provide typescript (p0def4), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/js@npm:15.6.3 doesn't provide nx (pe64a1), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/linter@npm:15.6.3 [46a57] doesn't provide nx (p103e4), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/linter@npm:15.6.3 [46a57] doesn't provide typescript (p84e0a), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/linter@npm:15.6.3 [a7da2] doesn't provide nx (pf756b), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/linter@npm:15.6.3 [a7da2] doesn't provide typescript (p66291), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/react@npm:15.6.3 doesn't provide nx (pb7836), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/react@npm:15.6.3 doesn't provide typescript (p4a5ef), requested by @phenomnomnominal/tsquery
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 210ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 245ms
➤ YN0000: ┌ Link step
➤ YN0008: │ @parcel/watcher@npm:2.0.4 must be rebuilt because its dependency tree changed
➤ YN0007: │ nx@npm:15.6.3 [f7a63] must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 1s 718ms
➤ YN0000: Done with warnings in 2s 279ms
```

### Additional Information

Note this issue is separate from supporting Yarn Plug'n'Play; this issue occurs when the `nodeLinker` setting is set to `node-modules`.

I'm happy to open a PR adding the peer dependencies to the nx packages.
