### ISSUE TITLE
Gitlab CI pipeline with distributed task execution doesn't fail on errors

### ISSUE THREAD

**Issue by cyclist82** [nrwl/nx#15612]
### Current Behavior

Thanks a lot for the great work.

Running a gitlab ci pipeline across dte-agents won't fail on errors.

The chained lint and build stages are failing, the pipeline job is running successfully. 

[Example pipeline](https://gitlab.com/cyclist82/nx-affected/-/jobs/3915800241)
<img width="827" alt="image" src="https://user-images.githubusercontent.com/37086112/224475652-5f9f2efa-cabb-49b4-984f-c401b5397acc.png">

### Expected Behavior

As described in the [docs](https://nx.dev/nx-cloud/reference/nx-cloud-cli#--stop-agents-on-failure) when a task fails the pipeline job should fail and the CI run should be terminated.

### GitHub Repo

https://gitlab.com/cyclist82/nx-affected

### Steps to Reproduce

1. Trigger CI pipeline run
2. `affected` and all `dte-agent` jobs run successfully

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : darwin arm64
   npm  : 9.5.0
   
   nx                      : 15.8.6
   @nrwl/js                : 15.8.6
   @nrwl/jest              : 15.8.6
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/angular           : 15.8.6
   @nrwl/cli               : 15.8.6
   @nrwl/cypress           : 15.8.6
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/nest              : 15.8.6
   @nrwl/node              : 15.8.6
   @nrwl/tao               : 15.8.6
   @nrwl/webpack           : 15.8.6
   @nrwl/nx-cloud          : 15.2.1
   typescript              : 4.9.5
```

### Failure Logs

```shell
[0KRunning with gitlab-runner 15.9.0~beta.115.g598a7c91 (598a7c91)[0;m
[0K  on blue-5.shared.runners-manager.gitlab.com/default -AzERasQ, system ID: s_8a38c517a741[0;m
[0K  feature flags: FF_USE_IMPROVED_URL_MASKING:true[0;m
section_start:1678525116:prepare_executor
[0K[0K[36;1mPreparing the "docker+machine" executor[0;m[0;m
[0KUsing Docker executor with image node:18 ...[0;m
[0KPulling docker image node:18 ...[0;m
[0KUsing docker image sha256:37b4077cbd8a1afc636235ae586c66414c03570a6e99bf985c9ced7075a75d9c for node:18 with digest node@sha256:8d9a875ee427897ef245302e31e2319385b092f1c3368b497e89790f240368f5 ...[0;m
section_end:1678525147:prepare_executor
[0Ksection_start:1678525147:prepare_script
[0K[0K[36;1mPreparing environment[0;m[0;m
Running on runner--azerasq-project-44227294-concurrent-0 via runner-azerasq-shared-1678525071-e9b0c980...
section_end:1678525150:prepare_script
[0Ksection_start:1678525150:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1m$ eval "$CI_PRE_CLONE_SCRIPT"[0;m
[32;1mFetching changes with git depth set to 20...[0;m
Initialized empty Git repository in /builds/cyclist82/nx-affected/.git/
[32;1mCreated fresh repository.[0;m
[32;1mChecking out 7a937045 as detached HEAD (ref is master)...[0;m

[32;1mSkipping Git submodules setup[0;m
section_end:1678525151:get_sources
[0Ksection_start:1678525151:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m[0;m
[0KUsing docker image sha256:37b4077cbd8a1afc636235ae586c66414c03570a6e99bf985c9ced7075a75d9c for node:18 with digest node@sha256:8d9a875ee427897ef245302e31e2319385b092f1c3368b497e89790f240368f5 ...[0;m
[32;1m$ npm ci[0;m
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

added 1961 packages, and audited 1962 packages in 1m

180 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[32;1m$ npx nx-cloud start-agent[0;m

 >  NX   Starting an agent for running Nx tasks


 >  NX   Running 1 tasks:

   - Task frontend:test Overrides: --ci --code-coverage

 

> nx run frontend:test --ci --code-coverage

frontend: [33m[1m[1m●[22m[1m Validation Warning[22m:[39m
frontend: [33m[39m
frontend: [33m  Unknown option [1m"coverageDirectory"[22m with value [1m"../../coverage/packages/frontend"[22m was found.[39m
frontend: [33m  This is probably a typing mistake. Fixing it will remove this message.[39m
frontend: [33m[39m
frontend: [33m  [1mConfiguration Documentation:[22m[39m
frontend: [33m  https://jestjs.io/docs/configuration[39m
frontend: [33m[39m
frontend: [0m[7m[1m[31m FAIL [39m[22m[27m[0m [0m[7m[37m frontend [39m[27m[0m [2mpackages/frontend/src/app/[22m[1mapp.component.spec.ts[22m
frontend:   [1m● [22mTest suite failed to run
frontend:     [96mpackages/frontend/src/app/app.component.spec.ts[0m:[93m3[0m:[93m36[0m - [91merror[0m[90m TS2307: [0mCannot find module './nx-welcome.component' or its corresponding type declarations.
frontend:     [7m3[0m import { NxWelcomeComponent } from './nx-welcome.component';
frontend:     [7m [0m [91m                                   ~~~~~~~~~~~~~~~~~~~~~~~~[0m
frontend: [1mTest Suites: [22m[1m[31m1 failed[39m[22m, 1 total
frontend: [1mTests:       [22m0 total
frontend: [1mSnapshots:   [22m0 total
frontend: [1mTime:[22m        6.774 s
frontend: [2mRan all test suites[22m[2m.[22m

 

 >  NX   Ran 1 tasks:

   - Task frontend:test Overrides: --ci --code-coverage  FAILED


 >  NX   Running 2 tasks:

   - Task frontend:lint 
   - Task frontend-e2e:lint 

 

> nx run frontend:lint


> nx run frontend-e2e:lint  [remote cache]


Linting "frontend-e2e"...

All files pass linting.

frontend: Linting "frontend"...
frontend: [0m[0m
frontend: [0m[4m/builds/cyclist82/nx-affected/packages/frontend/src/app/app.component.ts[24m[0m
frontend: [0m  [2m12:17[22m  [31merror[39m  Unexpected empty constructor  [2m@typescript-eslint/no-empty-function[22m[0m
frontend: [0m[0m
frontend: [0m[31m[1m✖ 1 problem (1 error, 0 warnings)[22m[39m[0m
frontend: [0m[31m[1m[22m[39m[0m
frontend: Lint errors found in the listed files.

 

 >  NX   Ran 2 tasks:

   - Task frontend:lint   FAILED
   - Task frontend-e2e:lint  CACHED 

section_end:1678525263:step_script
[0Ksection_start:1678525263:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1678525264:cleanup_file_variables
[0K[32;1mJob succeeded[0;m
```

**Comment by edolic** [comment]
We have a similar issue on Azure Devops Hosted Build Agents (Ubuntu).

If one task is failing within the task list, agents still continue to be idle and the build is not failing till all tasks are run.

```
# Build pipleline definition is used for pull request validation
variables:
  NX_BRANCH:  $(System.PullRequest.PullRequestId)
  NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
  NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: '3'
  isPhrasePr: $[contains(variables['System.PullRequest.SourceBranch'], 'update_i18n')]
trigger: none
pool:
  vmImage: ubuntu-latest
jobs:
- job: agent
  condition: and(always(), eq(variables.isPhrasePr, 'false'))
  strategy:
    parallel: 3
  steps:
    - script: yarn --pure-lockfile
      displayName: "Yarn"
    - script: yarn nx-cloud start-agent
      displayName: "Yarn start agents" 
  timeoutInMinutes: 120     
- job: pr
  condition: and(always(), eq(variables.isPhrasePr, 'false'))
  steps:
    - script: yarn --pure-lockfile
      displayName: "Yarn"
    - script: yarn nx-cloud start-ci-run --stop-agents-on-failure=true
      displayName: "Start-CI-Run"
    - script: node --max_old_space_size=8192 node_modules/@nrwl/cli/bin/nx.js affected --base=origin/master --head=HEAD --targets=build,test,lint,e2e,component-test --parallel=3 --skip-nx-cache=$(SKIP-NX-CACHE)
      displayName: DTE (Build,Test,Lint,E2E,ComponentTest)
    - script: yarn run deprecated-component-checker
      displayName: Deprecated Component Checker
    - task: CopyFiles@2
      condition: always()
      inputs:
        contents: '$(Build.SourcesDirectory)/dist/cypress/apps'
        targetFolder: $(Build.ArtifactStagingDirectory)/cypress
    - task: Bash@3
      displayName: 'Set CYPRESS_ARTIFACT_FOLDER_EXISTS'
      condition: always()
      inputs:
        targetType: 'inline'
        script: |
          if [ -d $(Build.ArtifactStagingDirectory)/cypress ]; then
          echo "##vso[task.setVariable variable=CYPRESS_ARTIFACT_FOLDER_EXISTS]true"
          fi
    - task: PublishBuildArtifacts@1
      condition: eq(variables.CYPRESS_ARTIFACT_FOLDER_EXISTS, 'true')
      displayName: 'Publish Cypress ScreenShots and Videos'
      inputs:
        PathtoPublish:  $(Build.ArtifactStagingDirectory)/cypress
        artifactName: CypressOutput
    - script: yarn nx-cloud stop-all-agents
      condition: always()
  timeoutInMinutes: 120
```
