### ISSUE TITLE
Azure pipeline nx affected/run-many fails

### ISSUE THREAD

**Issue by JelleBruisten** [nrwl/nx#15708]
### Current Behavior

On running 
`nx affected --target=build` or `nx run-many --target=build` 

In azure pipeline crashes on building, I tried with different targets `lint,test,build` nothing seems to work. The crash seems to not happen when running it locally on either a windows or linux machine. ( pipeline runs on `ubuntu-latest` ).
```
Could not find 'nx' module in this workspace. Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.

If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx
    at readCachedProjectGraph (/home/vsts/work/1/s/Frontend/node_modules/nx/src/project-graph/project-graph.js:28:15)
    at run (/home/vsts/work/1/s/Frontend/node_modules/nx/src/command-line/run.js:171:69)
    at requireCli (/home/vsts/work/1/s/Frontend/node_modules/nx/bin/run-executor.js:17:23)
    at Object.<anonymous> (/home/vsts/work/1/s/Frontend/node_modules/nx/bin/run-executor.js:12:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

If we would run the command locally, and then run the pipeline it does work because it will use the nx cloud/cache

### Expected Behavior

Should not crash in azure pipeline

### Steps to Reproduce

1.

### Nx Report

```shell
Node : 18.13.0                               
 OS   : win32 x64                             
 yarn : 3.2.4                                 
                                              
 nx : 15.6.3                                  
 @nrwl/angular : 15.6.3                       
 @nrwl/cypress : 15.6.3                       
 @nrwl/detox : Not Found                      
 @nrwl/devkit : 15.6.3                        
 @nrwl/esbuild : Not Found                    
 @nrwl/eslint-plugin-nx : 15.6.3              
 @nrwl/expo : Not Found                       
 @nrwl/express : Not Found                    
 @nrwl/jest : 15.6.3                          
 @nrwl/js : 15.6.3                            
 @nrwl/linter : 15.6.3                        
 @nrwl/nest : Not Found                       
 @nrwl/next : Not Found                       
 @nrwl/node : 15.6.3                          
 @nrwl/nx-cloud : 15.0.3                      
 @nrwl/nx-plugin : 15.6.3                     
 @nrwl/react : Not Found                      
 @nrwl/react-native : Not Found               
 @nrwl/rollup : 15.6.3                        
 @nrwl/schematics : Not Found                 
 @nrwl/storybook : 15.6.3                     
 @nrwl/web : 15.6.3                           
 @nrwl/webpack : 15.6.3                       
 @nrwl/workspace : 15.6.3                     
 @nrwl/vite : Not Found                       
 typescript : 4.9.5                           
 ---------------------------------------      
 Local workspace plugins:                     
       @cca/nx-tools                          
 ---------------------------------------      
 Community plugins:                           
       @alyle/ui: 13.4.0                      
       @ngneat/transloco: 4.2.5               
       @ngrx/component: 15.3.0                
       @ngrx/component-store: 15.3.0          
       @ngrx/data: 15.3.0                     
       @ngrx/effects: 15.3.0                  
       @ngrx/entity: 15.3.0                   
       @ngrx/eslint-plugin: 15.3.0            
       @ngrx/router-store: 15.3.0             
       @ngrx/store: 15.3.0                    
       @trellisorg/make-buildable: 0.0.12     
       @ngrx/schematics: 15.3.0               
       @ngrx/store-devtools: 15.3.0           
       @storybook/angular: 6.5.16
```

### Additional Information

Reverting back to nx version 15.6.x does seem to resolve the issue, moving to the latest version it does not work.

**Comment by JelleBruisten** [comment]
Pipeline itself:

`azure-pipeline.development.yaml`
```
trigger:
  branches:
    include:
      - development

resources:
  repositories:
    - repository: self
      name: <repoName>
      type: git
      ref: development
    - repository: GitOps
      name: GitOps
      type: git
      ref: master

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '<dockerRegistryServiceConnection>'
  imageRepository: '<imageRepoName>'
  containerRegistry: '<containerRegistry>'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  NX_BRANCH: 'development'

stages:
  - template: Build/templates/<app-name>.yaml@GitOps
    parameters:
      serviceName: 'Frontend'
      vmImage: $(vmImageName)
      repository: $(imageRepository)
      containerRegistry: $(dockerRegistryServiceConnection)
      environment: development
      angularConfig: 'development'
      targets: 'build,build-storybook'
```

Then the
`Build/templates/<app-name>.yaml`

```
parameters:
- name: version
  default: ''
- name: serviceName
- name: vmImage
- name: repository
- name: containerRegistry
- name: environment
- name: angularConfig
- name: targets
  default: 'build,build-storybook'

# Stage 1
stages:
- stage: Build
  displayName: Determine Version, Build and Push
  jobs:
    - job: Build
      displayName: Determine Version, Build and Push
      pool:
        vmImage: ${{ parameters.vmImage }}
      steps:
      - checkout: self
        fetchDepth: 0
      - checkout: GitOps
        path: 'GitOps/'
        clean: true
        persistCredentials: true

      # Install dependencies for building
      - script: yarn install --immutable
        displayName: 'Installing node modules / Post install'
        workingDirectory: $(Build.SourcesDirectory)/${{ parameters.serviceName }}  

      # Build Affected Libraries and Applications ( if not manually )
      - script: npx nx affected --targets=${{parameters.targets}} --configuration=${{ parameters.angularConfig }} --base=HEAD~1 
        condition: ne(variables['Build.Reason'], 'Manual')
        displayName: 'Build affected Libraries and Applications'
        workingDirectory: $(Build.SourcesDirectory)/${{ parameters.serviceName }}

      # Build All (if manually)
      - script: npx nx run-many --targets=${{parameters.targets}} --configuration=${{ parameters.angularConfig }}
        condition: eq(variables['Build.Reason'], 'Manual')
        displayName: 'Build all Libraries and Applications'
        workingDirectory: $(Build.SourcesDirectory)/${{ parameters.serviceName }}
      
      # Build & Push Docker Frontend
      <other steps for building docker images>


# Stage 2: 
<irrelevant for this issue will just update version numbers in our system such that they will be deployed>
```

**Comment by JelleBruisten** [comment]
In other pipelines for other environments we have

`targets: 'lint,test,build,build-storybook'` in that respective yaml file, but they use the same template. However even running with just build fails so that is not the issue in this case

**Comment by blidblid** [comment]
I'm seeing the exact same exception in a Gitlab pipeline running `"@nrwl/workspace": "15.8.6"`. Locally everything works fine, but every job fails in the pipeline.

```
.base:
  image: node:16.14.0
  interruptible: true
  stage: build
  tags:
    - gcp-client
  before_script:
    - apt-get update -qq && apt-get install

stages:
  - install
  - build

Install:
  extends:
    - .base
  stage: install
  cache:
    - <<: *node_modules_cache
      policy: push
    - <<: *cypress_cache
      policy: push
  script:
    - yarn install --force --frozen-lockfile --no-progress

Build:
  extends:
    - .base
  cache:
    - <<: *node_modules_cache
  script:
    - npx nx build
```

**Comment by JelleBruisten** [comment]
@blidblid running a previous version in my case `15.6.x` works in gitlab?

**Comment by blidblid** [comment]
I ran `nx migrate` to upgrade from `15.3.0` to `15.8.6`. The pipeline had no issues before the migration.

**Comment by JelleBruisten** [comment]
I did some testing and when migrated to `15.7.1` it still worked correctly it seems to be introduced in the `15.8.*` release

**Comment by dash-tobin** [comment]
+1 on moving from 15.6.2 to 15.8.9 using migrate command.

**Comment by JelleBruisten** [comment]
Managed to reproduce it in a smaller pipeline:

Used the create ci-workflow as a basis for this one:

```
trigger:
  - none

resources:
  repositories:
    - repository: self
      name: Frontend
      type: git
      ref: development

variables:
  CI: 'true'
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(System.PullRequest.PullRequestNumber)
    TARGET_BRANCH: $[replace(variables['System.PullRequest.TargetBranch'],'refs/heads/','origin/')]
    BASE_SHA: $(git merge-base $(TARGET_BRANCH) HEAD)

  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(Build.SourceBranchName)
    BASE_SHA: $(git rev-parse HEAD~1)

  HEAD_SHA: $(git rev-parse HEAD)

stages:
  - stage: main
    displayName: Main
    jobs:
      - job: build
        pool:
          vmImage: 'ubuntu-latest'
        displayName: test
        steps:
          - checkout: self
            fetchDepth: 0

          - script: yarn install --immutable
            displayName: NPM Install Dependencies

          - script: yarn exec nx run-many --target=lint --parallel=3 --skip-nx-cache
            displayName: Run lint

          - script: yarn exec nx run-many --target=test --parallel=3 --code-coverage --skip-nx-cache
            displayName: Run test

          - script: yarn exec nx run-many --target=build --parallel=3 --skip-nx-cache
            displayName: Run build
```
