### ISSUE TITLE
Maximum callstack exceeded when running npm install -g  @nrwl/cli

### ISSUE THREAD

**Issue by sabaimran** [nrwl/nx#15869]
### Current Behavior

When I run `npm install -g @nrwl/cli`, I get the error `npm ERR! Maximum call stack size exceeded`. For context, this is specifically happening in a `.github` action. This started about ~2 hours ago, which I believe correlates with the time of [this new release 15.8.8](https://github.com/nrwl/nx/releases/tag/15.8.8)

```
Run npm install -g @nrwl/cli
  npm install -g @nrwl/cli
  npm install -g nx
  shell: /usr/bin/bash -e {0}
##[debug]/usr/bin/bash -e /home/runner/work/_temp/4231feae-a5c9-405a-ad35-f1a06653a077.sh
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-linux-arm64-musl@15.8.8 (node_modules/@nrwl/cli/node_modules/nx/node_modules/@nrwl/nx-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-linux-arm64-musl@15.8.8: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-darwin-x64@15.8.8 (node_modules/@nrwl/cli/node_modules/nx/node_modules/@nrwl/nx-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-darwin-x64@15.8.8: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-darwin-arm64@15.8.8 (node_modules/@nrwl/cli/node_modules/nx/node_modules/@nrwl/nx-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-darwin-arm64@15.8.8: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-linux-arm-gnueabihf@15.8.8 (node_modules/@nrwl/cli/node_modules/nx/node_modules/@nrwl/nx-linux-arm-gnueabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-linux-arm-gnueabihf@15.8.8: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-linux-arm64-gnu@15.8.8 (node_modules/@nrwl/cli/node_modules/nx/node_modules/@nrwl/nx-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-linux-arm64-gnu@15.8.8: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-win32-arm64-msvc@15.8.8 (node_modules/@nrwl/cli/node_modules/nx/node_modules/@nrwl/nx-win32-arm64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-win32-arm64-msvc@15.8.8: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-win32-x64-msvc@15.8.8 (node_modules/@nrwl/cli/node_modules/nx/node_modules/@nrwl/nx-win32-x64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-win32-x64-msvc@15.8.8: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})

npm ERR! Maximum call stack size exceeded
```

github action configuration
```
jobs:
  build-front-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: '0'

      - name: Set up Node 14
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '14.18'

      - name: Set up NX
        run: |
          npm install -g @nrwl/cli@14.8.8
          npm install -g nx
```

### Expected Behavior

I expect it to install without any errors. Below output is from a successful install from a previous iteration.

```
Run npm install -g @nrwl/cli

> @parcel/watcher@2.0.4 install /opt/hostedtoolcache/node/14.18.3/x64/lib/node_modules/@nrwl/cli/node_modules/@parcel/watcher
> node-gyp-build


> nx@15.8.7 postinstall /opt/hostedtoolcache/node/14.18.3/x64/lib/node_modules/@nrwl/cli/node_modules/nx
> node ./bin/compute-project-graph

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-darwin-x64@15.8.7 (node_modules/@nrwl/cli/node_modules/nx/node_modules/@nrwl/nx-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-darwin-x64@15.8.7: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-darwin-arm64@15.8.7 (node_modules/@nrwl/cli/node_modules/nx/node_modules/@nrwl/nx-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-darwin-arm64@15.8.7: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-linux-arm64-gnu@15.8.7 (node_modules/@nrwl/cli/node_modules/nx/node_modules/@nrwl/nx-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-linux-arm64-gnu@15.8.7: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-linux-arm64-musl@15.8.7 (node_modules/@nrwl/cli/node_modules/nx/node_modules/@nrwl/nx-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-linux-arm64-musl@15.8.7: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-win32-arm64-msvc@15.8.7 (node_modules/@nrwl/cli/node_modules/nx/node_modules/@nrwl/nx-win32-arm64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-win32-arm64-msvc@15.8.7: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-linux-arm-gnueabihf@15.8.7 (node_modules/@nrwl/cli/node_modules/nx/node_modules/@nrwl/nx-linux-arm-gnueabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-linux-arm-gnueabihf@15.8.7: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-win32-x64-msvc@15.8.7 (node_modules/@nrwl/cli/node_modules/nx/node_modules/@nrwl/nx-win32-x64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-win32-x64-msvc@15.8.7: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})

+ @nrwl/cli@15.8.7
added 126 packages from 177 contributors in 7.767s
/opt/hostedtoolcache/node/14.18.3/x64/bin/nx -> /opt/hostedtoolcache/node/14.18.3/x64/lib/node_modules/nx/bin/nx.js
```

### Steps to Reproduce

Create a github action with the follow configuration:

```
name: Testing nrwl/cli installation issues
on:
  workflow_dispatch:

  pull_request:
    types: [ opened ]

jobs:
  build-front-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: '0'

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v2

      - name: Set up Node 14
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '14.18'

      - name: Set up NX
        run: |
          npm install -g @nrwl/cli@14.8.8
          npm install -g nx

```

### Nx Report

```shell
>  NX  Report complete - copy this into the issue template

  Node : 14.18.0
  OS   : darwin arm64
  npm  : 6.14.15

  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : 12.9.0
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 12.3.13
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

### Failure Logs

```shell
`npm ERR! Maximum call stack size exceeded`
```

### Additional Information

The issue is happening consistently in a github action across all branches, including branches that were previously passing this build. I tried rolling back the version of nrwl/cli to 14.8.8 with `npm install -g @nrwl/cli@14.8.8` in the action, but this results in another error.

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /opt/hostedtoolcache/node/14.18.3/x64/lib/node_modules/nx/node_modules/@nrwl/tao/index
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/opt/hostedtoolcache/node/14.18.3/x64/lib/node_modules/nx/node_modules/@nrwl/tao/index'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```
