### ISSUE TITLE
npx nx affected --target=test --base=remotes/origin/master , doesn't work in a bitbucket pipeline

### ISSUE THREAD

**Issue by romanpastu** [nrwl/nx#15897]
### Current Behavior

Whenever im checked out  a branch, lets say it is "feature-branch" ,  and I run the following command

`npx nx affected --target=test --base=remotes/origin/master`

The tests won't run, if I had no changes in my tests when compared with the master, as expected

But in my bitbucket pipeline, i have this job

```
pipelines:
    - parallel:
        - step:
            caches:
              - node-cache
            script:
              - apk update && apk add git
              - git fetch
              - git branch -a
              - npx nx affected --target=test --base=remotes/origin/master
```

It compares against master, i have a full clone, so I can see the branches against which is compares in git branch -a, and they are displayed correctly. And the tests will always run, aren't they supposed to not run if no changes happen in the tests?

```
clone:
  depth: full

```

Is there something im missing?

### Expected Behavior

Whenever          
`  - npx nx affected --target=test --base=remotes/origin/master`
Is run in the pipeline belongin to a feature branch, if tests have not changed when comparing with master branch, tests should not run, but they always run.

### Steps to Reproduce

Add the following script in the bitbucket pipelines of a feature , and expect it to no run when there are no changes in master regarding tests

```
            script:
              - apk update && apk add git
              - git fetch
              - git branch -a
              - npx nx affected --target=test --base=remotes/origin/master
```

### Nx Report

```shell
Node : 16.14.0
   OS   : linux x64
   yarn : 3.2.0
   
   nx          : 15.8.7
   @nrwl/cli   : 15.8.7
   @nrwl/tao   : 15.8.7
   typescript  : 4.6.2
```
