### ISSUE TITLE
DTE orchestrator reports "all jobs done" before agents actually finished their work

### ISSUE THREAD

**Issue by maxfriedmann** [nrwl/nx#16425]
### Current Behavior

This morning I saw this issue showing up in our main gitlab pipeline:

![image](https://user-images.githubusercontent.com/2809483/233276814-a53fd553-640a-434d-9263-9c2c8a337c41.png)

The orchestrator reports "all jobs done" before 2/6 agents actually finished their work. We're connected to nx cloud obviously and all jobs are actually posted there correctly. 

Unfortunately, if one of the remaining jobs fail (after the orchestrator stopped and reported "all good"), the orchestrator job in gitlab will still succeed and since the agents always succeed nevertheless they have failed jobs, it looks like everything is fine.

### Expected Behavior

The dte orchestrator should wait until all agents have finished their work.

### Steps to Reproduce

The orchestrator configuration:

```yaml
Nx DTE Orchestrator:
  variables:
    NX_CLOUD_DISTRIBUTED_EXECUTION: "true"
  stage: build
  script:
    - npx nx-cloud start-ci-run
    - npx nx-cloud record -- npx nx workspace-lint --base=$NX_BASE --head=$NX_HEAD
    - npx nx-cloud record -- npx nx format:check --base=$NX_BASE --head=$NX_HEAD
    - npx nx-cloud record -- npm audit --production --audit-level=moderate
    - npx nx-cloud record -- npm audit --audit-level=moderate
    - npx nx run-many --all --target=build --parallel=1 & npx nx run-many --all --target=lint --quiet --parallel=1 & npx nx run-many --all --target=test --ci --code-coverage --forceExit --parallel=1 & npx nx run-many --all --target=playwright  --parallel=1
    - npx nx-cloud stop-all-agents 
```

The agent configuration:
```yaml
Nx Agent:
  parallel: 6
  script:
    - npx nx-cloud start-agent
  stage: build
```

### Nx Report

```shell
Node : 18.12.1
OS   : win32 x64
npm  : 8.19.2

nx                      : 15.8.5
@nrwl/js                : 15.8.5
@nrwl/jest              : 15.8.5
@nrwl/linter            : 15.8.5
@nrwl/workspace         : 15.8.5
@nrwl/angular           : 15.8.5
@nrwl/cli               : 15.8.5
@nrwl/cypress           : 15.8.5
@nrwl/devkit            : 15.8.5
@nrwl/esbuild           : 15.8.5
@nrwl/eslint-plugin-nx  : 15.8.5
@nrwl/express           : 15.8.5
@nrwl/nest              : 15.8.5
@nrwl/node              : 15.8.5
@nrwl/rollup            : 15.8.5
@nrwl/tao               : 15.8.5
@nrwl/web               : 15.8.5
@nrwl/webpack           : 15.8.5
@nrwl/nx-cloud          : 15.3.5
typescript              : 4.9.5
---------------------------------------
Community plugins:
ng2-charts       : 4.1.1
@currents/nx     : 1.0.0-beta.2
@nativescript/nx : 3.0.18
ng-mocks         : 14.7.1
```

### Additional Information

I've seen some gitlab pipelines which actually were "successful" but had failing distributed nx jobs. I am still browsing the recent pipelines to see when this issue occurred the first time.
