### ISSUE TITLE
Nx Cloud failing npm ci in nx@16.0.0 workspace

### ISSUE THREAD

**Issue by nongrata081** [nrwl/nx#16632]
### Current Behavior

Nx Cloud fails on `npm ci` in a freshly scaffolded nx-workspace with nx@16.0.0 and next.js@13.3.0.

### Expected Behavior

Nx Cloud should run npm ci, npm dependencies should be installed without errors.

### Steps to Reproduce

1. `npx create-nx-workspace@16.0.0 <workspace-name> --allPrompts=true` (scaffold with github actions + nx cloud CI)
2. `npm i -D @nx/next`
3. `npx nx generate @nx/next:application <nextjs-app-name> --style=@emotion/styled --no-interactive`
4. commit, push to a repo in github, create a Pull Request to develop branch
5. Error on `npm ci` step in Nx Cloud

### Nx Report

```shell
Node   : 18.16.0
   OS     : linux x64
   npm    : 9.5.1
   Hasher : Native
   
   nx                      : 16.0.0
   @nx/js                  : 16.0.0
   @nrwl/js                : 16.0.0
   @nx/jest                : 16.0.0
   @nrwl/jest              : 16.0.0
   @nx/linter              : 16.0.0
   @nrwl/linter            : 16.0.0
   @nx/workspace           : 16.0.0
   @nrwl/workspace         : 16.0.0
   @nx/cypress             : 16.0.0
   @nrwl/cypress           : 16.0.0
   @nx/devkit              : 16.0.0
   @nrwl/devkit            : 16.0.0
   @nx/eslint-plugin       : 16.0.0
   @nrwl/eslint-plugin-nx  : 16.0.0
   @nx/next                : 16.0.0
   @nrwl/next              : 16.0.0
   @nx/react               : 16.0.0
   @nrwl/react             : 16.0.0
   @nrwl/tao               : 16.0.0
   @nx/web                 : 16.0.0
   @nrwl/web               : 16.0.0
   @nrwl/nx-cloud          : 16.0.5
   nx-cloud                : 16.0.5
   typescript              : 4.9.5
```

### Failure Logs

```shell
Install dependencies

Running npm ci
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: webpack@5.81.0 from lock file
npm ERR! Missing: @types/eslint-scope@3.7.4 from lock file
npm ERR! Missing: @types/estree@1.0.1 from lock file
npm ERR! Missing: @webassemblyjs/ast@1.11.5 from lock file
npm ERR! Missing: @webassemblyjs/wasm-edit@1.11.5 from lock file
npm ERR! Missing: @webassemblyjs/wasm-parser@1.11.5 from lock file
npm ERR! Missing: acorn-import-assertions@1.8.0 from lock file
npm ERR! Missing: chrome-trace-event@1.0.3 from lock file
npm ERR! Missing: es-module-lexer@1.2.1 from lock file
npm ERR! Missing: events@3.3.0 from lock file
npm ERR! Missing: glob-to-regexp@0.4.1 from lock file
npm ERR! Missing: loader-runner@4.3.0 from lock file
npm ERR! Missing: schema-utils@3.1.2 from lock file
npm ERR! Missing: terser-webpack-plugin@5.3.7 from lock file
npm ERR! Missing: watchpack@2.4.0 from lock file
npm ERR! Missing: webpack-sources@3.2.3 from lock file
npm ERR! Missing: @types/eslint@8.37.0 from lock file
npm ERR! Missing: @webassemblyjs/helper-numbers@1.11.5 from lock file
npm ERR! Missing: @webassemblyjs/helper-wasm-bytecode@1.11.5 from lock file
npm ERR! Missing: @webassemblyjs/floating-point-hex-parser@1.11.5 from lock file
npm ERR! Missing: @webassemblyjs/helper-api-error@1.11.5 from lock file
npm ERR! Missing: @xtuc/long@4.2.2 from lock file
npm ERR! Missing: @webassemblyjs/helper-buffer@1.11.5 from lock file
npm ERR! Missing: @webassemblyjs/helper-wasm-section@1.11.5 from lock file
npm ERR! Missing: @webassemblyjs/wasm-gen@1.11.5 from lock file
npm ERR! Missing: @webassemblyjs/wasm-opt@1.11.5 from lock file
npm ERR! Missing: @webassemblyjs/wast-printer@1.11.5 from lock file
npm ERR! Missing: @webassemblyjs/ieee754@1.11.5 from lock file
npm ERR! Missing: @webassemblyjs/leb128@1.11.5 from lock file
npm ERR! Missing: @webassemblyjs/utf8@1.11.5 from lock file
npm ERR! Missing: @xtuc/ieee754@1.2.0 from lock file
npm ERR! Missing: jest-worker@27.5.1 from lock file
npm ERR! Missing: schema-utils@3.1.2 from lock file
npm ERR! Missing: terser@5.17.1 from lock file
npm ERR! Missing: @jridgewell/source-map@0.3.3 from lock file
npm ERR! Missing: commander@2.20.3 from lock file
npm ERR! Missing: source-map-support@0.5.21 from lock file
npm ERR! Missing: supports-color@8.1.1 from lock file
npm ERR! Missing: ajv@6.12.6 from lock file
npm ERR! Missing: ajv-keywords@3.5.2 from lock file
npm ERR! Missing: json-schema-traverse@0.4.1 from lock file
npm ERR! Missing: source-map@0.6.1 from lock file
npm ERR! Missing: ajv@6.12.6 from lock file
npm ERR! Missing: ajv-keywords@3.5.2 from lock file
npm ERR! Missing: json-schema-traverse@0.4.1 from lock file
npm ERR! 
npm ERR! Clean install a project
npm ERR! 
npm ERR! Usage:
npm ERR! npm ci
npm ERR! 
npm ERR! Options:
npm ERR! [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
npm ERR! [-E|--save-exact] [-g|--global]
npm ERR! [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
npm ERR! [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm ERR! 
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR! 
npm ERR! Run "npm help ci" for more info

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-04-28T08_43_23_008Z-debug-0.log
Error: Process completed with exit code 1.


...

Stop all running agents for this CI run

npx nx-cloud stop-all-agents
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    NX_CLOUD_DISTRIBUTED_EXECUTION: true
    NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3
    NX_BRANCH: 26
    NX_CLOUD_ACCESS_TOKEN: 
    NX_CLOUD_AUTH_TOKEN: 
    NPM_TOKEN: 
    NX_BASE: 6b2fb81f964ee1c10575625ba0114ca66e2f5d75
    NX_HEAD: 84156824432f334e3072e777bad436c5ba31fc28
    VOLTA_HOME: /opt/hostedtoolcache/volta/1.1.1/x64
npm WARN exec The following package was not found and will be installed: nx-cloud@16.0.5
NX CLOUD ERROR
---------------------------------------
This version of Nx Cloud is incompatible with the @nrwl/* and @nx/* packages in your workspace, or Nx was not installed properly.

Verify your install step was successful, and if it was,
match your @nrwl/nx-cloud version to the same major version of your @nx/* and @nrwl/* packages and try again.
---------------------------------------
Error: Process completed with exit code 1.
```

**Comment by StalkAltan** [comment]
Hey @nongrata081, can you check this error from the top of your log and let us know if this fixes the problem?

```
Running npm ci
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```

GH Actions doesn't make it very easy to spot these install errors, so we added 
```
...
Verify your install step was successful, and if it was,
...
```
to the runner output.

**Comment by nongrata081** [comment]
my bad, edited the ci.yml that was generated and it worked:

```
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    with:
      number-of-agents: 3
      init-commands: |
        npx nx-cloud start-ci-run --stop-agents-after="test" --agent-count=3
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
      node-version: 'v18.16.0'
      npm-version: '9.5.1'
      runs-on: 'ubuntu-22.04'

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.3
    with:
      number-of-agents: 3
```
