### ISSUE TITLE
Yarn Berry generateLockfile error

### ISSUE THREAD

**Issue by veimox** [nrwl/nx#17440]
### Current Behavior

When using `generateLockfile` on the `@nx/next:build` fails with 

```sh
Original error: Cannot read properties of undefined (reading 'has')
   TypeError: Cannot read properties of undefined (reading 'has')
    at <secret>/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:238:47
    at Map.forEach (<anonymous>)
    at mapSnapshots (<secret>/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:229:17)
    at stringifyYarnLockfile (<secret>/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:139:23)
    at createLockFile (<secret>/node_modules/nx/src/plugins/js/lock-file/lock-file.js:133:60)
    at <secret>/node_modules/@nx/next/src/executors/build/build.impl.js:64:54
    at Generator.next (<anonymous>)
    at <secret>/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (<secret>/node_modules/tslib/tslib.js:163:16)
```

## Research
I have put a breakpoint to debug the issue and the problem comes when it tries to resolve the package `string-width-cjs`. The problem is that in our `yarn.lock` the entry is such:

```yml
"string-width-cjs@npm:string-width@^4.2.0, string-width@npm:^1.0.2 || 2 || 3 || 4, string-width@npm:^4.0.0, string-width@npm:^4.1.0, string-width@npm:^4.2.0, string-width@npm:^4.2.2, string-width@npm:^4.2.3":
  version: 4.2.3
  resolution: "string-width@npm:4.2.3"
  dependencies:
    emoji-regex: ^8.0.0
    is-fullwidth-code-point: ^3.0.0
    strip-ansi: ^6.0.1
  checksum: e52c10dc3fbfcd6c3a15f159f54a90024241d0f149cf8aed2982a2d801d2e64df0bf1dc351cf8e95c3319323f9f220c16e740b06faecd53e2462df1d2b5443fb
  languageName: node
  linkType: hard
```

As it can be seen the package is `string-width-cjs` but the resolution is done with `string-width@npm:4.2.3`. Note the package name difference. The object `existingKeys` does not contain the `-cjs` one and when it tries to [access it here](https://github.com/nrwl/nx/blob/master/packages/nx/src/plugins/js/lock-file/yarn-parser.ts#L351) by name it fails. That outputs an `undefined` that happens to lack the `.has()` method.

I guess this is a bit of an edge case with conflicting package names and resolutions and I can resolve it locally but I guess that  it exposes some issue with the existing population logic of `existingKeys`.

### Expected Behavior

Generates an pruned `package.json` without errors

### GitHub Repo

https://github.com/veimox/nx-17440

### Steps to Reproduce

Look at the README of https://github.com/veimox/nx-17440

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.19.0
   OS     : darwin x64
   yarn   : 3.6.0
   Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/nest           : 16.3.2
   @nx/next           : 16.3.2
   @nx/node           : 16.3.2
   @nx/plugin         : 16.3.2
   @nx/react          : 16.3.2
   @nx/storybook      : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 4.9.5
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)
