### ISSUE TITLE
Lockfile generated by `@nx/next:build` is invalid

### ISSUE THREAD

**Issue by ganlhi** [nrwl/nx#17873]
### Current Behavior

When using Yarn 3 in a Nx workspace, running `@nx/next:build` with `generateLockfile` generates a lockfile that contains an empty package name:

```
"":
  version: 5.1.6
  resolution: "typescript@patch:typescript@npm%3A5.1.6#~builtin<compat/typescript>::version=5.1.6&hash=5da071"
  bin:
    tsc: bin/tsc
    tsserver: bin/tsserver
  checksum: f53bfe97f7c8b2b6d23cf572750d4e7d1e0c5fff1c36d859d0ec84556a827b8785077bc27676bf7e71fae538e517c3ecc0f37e7f593be913d884805d931bc8be
  languageName: node
  linkType: hard
```

### Expected Behavior

The generated lockfile should be valid. 

### GitHub Repo

https://github.com/ganlhi/nx-next-lockfile-issue

### Steps to Reproduce

1. Run `yarn install` to install dependencies with Yarn 3
2. Run `nx run my-app:build:production`
3. Look at `dist/packages/my-app/yarn.lock`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.13.0
   OS     : darwin-arm64
   yarn   : 3.6.0

   nx                 : 16.4.1
   @nx/js             : 16.4.1
   @nx/jest           : 16.4.1
   @nx/linter         : 16.4.1
   @nx/workspace      : 16.4.1
   @nx/cypress        : 16.4.1
   @nx/devkit         : 16.4.1
   @nx/eslint-plugin  : 16.4.1
   @nx/next           : 16.4.1
   @nx/react          : 16.4.1
   @nrwl/tao          : 16.4.1
   @nx/web            : 16.4.1
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)
