### ISSUE TITLE
Lockfile generated by `@nx/vite:build` is invalid with patched dependencies present

### ISSUE THREAD

**Issue by rosettaroberts-impact** [nrwl/nx#18012]
### Current Behavior

When using Yarn 3 in a Nx workspace, running @nx/vite:build with generateLockfile generates a lockfile that contains an empty package name when a dependency is patched.
```
"":
  version: 0.27.0
  resolution: "@growthbook/growthbook@patch:@growthbook/growthbook@npm%3A0.27.0#./.yarn/patches/@growthbook-growthbook-npm-0.27.0-3197004b39.patch::version=0.27.0&hash=07ade4&locator=%40nx-vite-lockfile-issue%2Fsource%40workspace%3A."
  dependencies:
    dom-mutator: ^0.5.0
  checksum: 3f972c2c8f9ee4667c56457a400b17f9dd5ae2c26e32213704a9eb7855bc2605866e41935dbf94389d64f7f11fdb716445cf484a42051af2bc2665b299b787c7
  languageName: node
  linkType: hard
```

Empty package names are invalid and cause `yarn` to error out when they are present:
```
Internal Error: Invalid descriptor ()
    at WA (/home/rose/.volta/tools/image/yarn/3.5.1/bin/yarn.js:390:24431)
    at je.setupResolutions (/home/rose/.volta/tools/image/yarn/3.5.1/bin/yarn.js:439:1283)
    at async je.find (/home/rose/.volta/tools/image/yarn/3.5.1/bin/yarn.js:436:1518)
    at async yu.execute (/home/rose/.volta/tools/image/yarn/3.5.1/bin/yarn.js:499:11751)
    at async yu.validateAndExecute (/home/rose/.volta/tools/image/yarn/3.5.1/bin/yarn.js:345:664)
    at async Hn.run (/home/rose/.volta/tools/image/yarn/3.5.1/bin/yarn.js:359:2057)
    at async Hn.runExit (/home/rose/.volta/tools/image/yarn/3.5.1/bin/yarn.js:359:2241)
    at async i (/home/rose/.volta/tools/image/yarn/3.5.1/bin/yarn.js:446:12054)
    at async t (/home/rose/.volta/tools/image/yarn/3.5.1/bin/yarn.js:446:10283)
```

### Expected Behavior

`@nx/vite:build` should be generating valid `yarn.lock` files when one of the dependencies is patched.

### GitHub Repo

https://github.com/rosettaroberts-impact/nx-vite-lockfile-issue

### Steps to Reproduce

Ensure that yarn 3 and node 18 are installed:
```
git clone https://github.com/rosettaroberts-impact/nx-vite-lockfile-issue.git
yarn dlx nx build app

cd dist/apps/app
# Yarn errors out because the generated lock file is invalid
yarn
```

### Nx Report

```shell
Node   : 18.16.1
   OS     : linux-x64
   yarn   : 3.6.1
   
   nx (global)        : 16.5.0
   nx                 : 16.5.0
   @nx/js             : 16.5.0
   @nx/linter         : 16.5.0
   @nx/workspace      : 16.5.0
   @nx/cypress        : 16.5.0
   @nx/eslint-plugin  : 16.5.0
   @nx/vite           : 16.5.0
   @nx/web            : 16.5.0
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This likely has the same underlying cause as https://github.com/nrwl/nx/issues/17873.
