### ISSUE TITLE
v16.7.4 - Cannot find module @nx/nx-linux-x64-gnu

### ISSUE THREAD

**Issue by xeinebiu** [nrwl/nx#19000]
### Current Behavior

npm ERR! code 1
npm ERR! path /home/runner/work/frontend/frontend/node_modules/nx
npm ERR! command failed
npm ERR! command sh -c node ./bin/post-install
npm ERR! /home/runner/work/frontend/frontend/node_modules/nx/src/native/index.js:244
npm ERR!     throw loadError
npm ERR!     ^
npm ERR! 
npm ERR! Error: Cannot find module '@nx/nx-linux-x64-gnu'

### Expected Behavior

After upgrading the NX workspace, the build started to fail.

### Steps to Reproduce

1. Upgrade to latest Version
2. Create a Github action
```
      - name: Setup NodeJS
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm ci
        env:
          NX_NON_NATIVE_HASHER: true
```
3. The npm ci should fail

### Nx Report

```shell
Node   : 18.16.1
   OS     : darwin-arm64
   npm    : 9.5.1
   
   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/react          : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/vite           : 16.7.4
   @nx/web            : 16.7.4
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information
Switching back to v16.3.2 for now as this build works on ubuntu.

it fails on ubuntu (github action)
