### ISSUE TITLE
Azure Devops (pipelines) for deploying multi apps (angular and nestjs) ?

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#1930]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Hi, I am hoping that somebody is doing something similar and can share there azure-pipelines.yml file :-)

Trying to use azure pipelines to build the projects (there is 1 angular and 1 nestjs) and automatically release.

The thing where I am getting confused is, technically there are 2 apps, and each push to master causes a build, but I only want to build and release the artifact if its changed.

Anybody doing something with the azure pipelines ?

I presume that I need to use the affected scripts and build only if changed but then how for the release artifacts to support deploying 1 or more apps.

Look forward to any insight anyone has :-)

I am at a loss right now.

**Comment by elvirdolic** [comment]
We are doing by adding tags to the build. Each affected app is added as tag. You can use azure devops rest api for that (poweshell or node.js there is a node client available). You need then for each app a release pipeline. For each release pipeline you can define artifact filters based on build tags.

**Comment by iangregsondev** [comment]
Thanks @elvirdolic , I am still learning azure :-) I presume then I need to write a small nodejs script to call the rest service. Would you have the link to the docs for that ?

The tag that is added, is a one off tag, i mean, right now the pipeline we detect a new PUSH on github and run the yaml file, so I presume that the filters need to be added on the yml level ? to check for the tag - and next push the tags are reset ?

**Comment by iangregsondev** [comment]
I think I have the concept more or less now :-) The tags are added to the buildId. And I am able to use the AZ command line tools to add the tags using a buildID.

I will attempt it after doing a little further investigation.

**Comment by WangZishi** [comment]
@iangregsondev I'm also trying to do this. This is how I build angular applications.
![image](https://user-images.githubusercontent.com/8288105/67136981-eab4a400-f260-11e9-80cd-63f02b425842.png)

**Comment by iangregsondev** [comment]
This has been really helpful 

Thanks

**Comment by vsavkin** [comment]
@mbriggs Matt is putting together an example.

**Comment by NiklasPor** [comment]
We've also been searching for this and built it ourself. We use build tags and specify release triggers based on the build tag. To add the tags inside the build, we simply use this single line of bash:
```
node node_modules/@nrwl/cli/bin/nx.js affected:apps --base=HEAD~1  --head=HEAD | grep -E '( - )(\w|-|\d|_)+' | sed -E 's/ - /##vso[build.addbuildtag]/g'
```

It works for app names containing numbers, letters, `-` and `_`.
After that simply create different release pipelines for your different apps and use the build tag as a trigger :)

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by GreatHawkeye** [comment]
Hi,

I'm struggling alot with this. 
I don't understand how to make it work. 

I've created a release pipeline which is linked on my monorepo and I added a build tag which is the name of my application.

![image](https://user-images.githubusercontent.com/29467803/83348094-dd4cb580-a329-11ea-93ac-f842ab6dfa88.png)

Is that correct?

Now I believe I should add a build tag for each artifact that is created while running the build pipeline. Am I understanding it correctly?

If yes, then I really don't understand how to do so.
If you could help me on this, it's driving me crazy.

When and how am I supposed to add those build tags?

Many thanks

**Comment by elvirdolic** [comment]
What we did is to read all folders from the dist dir which contains all builded apps then we use the azure devops rest api to add the build tags based on the folder names

**Comment by NiklasPor** [comment]
@GreatHawkeye we're using the `affected:apps` command by nx to add these tags.

Simply have a look at the bash command I wrote in december. We're using it to tag the builds. You'll just have to include the execution of it in your build pipeline:

https://github.com/nrwl/nx/issues/1930#issuecomment-567976528

**Comment by GreatHawkeye** [comment]
@NiklasPor  Thank you for your answer.
Is the following correct? Because it looks like doing nothing on the pipeline logs.

```
  - job: Build
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'
      - task: Npm@1
        displayName: 'npm install'
      - pwsh: 'npm run nx affected -- --target=build --parallel --base=origin/master --prod'
        displayName: 'Running build'
      - pwsh: |
          npm run nx affected:apps -- --base=HEAD~1  --head=HEAD | grep -E '( - )(\w|-|\d|_)+' | sed -E 's/ - /##vso[build.addbuildtag]/g'
        displayName: 'Adding build tags'
```

**Comment by NiklasPor** [comment]
@GreatHawkeye looks pretty solid, except you'll need to change the base to match your other affected command. Instead of `--base=origin/master` use your `--base=origin/master`.

**Comment by GreatHawkeye** [comment]
@NiklasPor , awesome, it worked!!
Thank you very much. It added two tags as my workspace contains 2 apps.

So if I understand it correctly, what just happened is that the entire build has now 2 tags linked to it.
Now, I've created two release pipelines which are linked to my monorepo, each has a build tag filter with the name of their associated app.

How does the build tag filter works? In my (poor) understanding, the generated build has both tags, how can my release pipelines filter the correct folder to deploy (which is `dist/${app-name}`?

**Comment by NiklasPor** [comment]
Yes, you'll now need different release pipelines for the different tagged builds. One pipeline for each application. (We also have the different stages of that release inside that pipeline).

Sadly you'll have to do the extracting yourself. E.g. copying the files from one app folder to wherever you wanna do release stuff with them.

You can extract the common tasks shared by all release pipelines into task groups, so that you'll only have to write that once.

**Comment by GreatHawkeye** [comment]
Okay so I believe I should `zip` each one of my app and publish the artifact in my artifact directory?

I found this snippet  : 

```
  - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)/dist/apps/app-name'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'

      - publish: '$(Build.ArtifactStagingDirectory)'
        artifact: app-name
```

I'm guessing I have to replace `app-name` by the correct folders. 

Does that make sense if I store the result of your `nx affected:apps [...]` commands in an array in order to loop through it and executing the zip and publish tasks on each item of the array?
