### ISSUE TITLE
bump nx-cloud-main.yml version from v0.13.1 to 0.14.0

### ISSUE THREAD

**Issue by acfasj** [nrwl/nx#20393]
## Description

When I use nx generate ci-workflow for github, I got the teampte code:
```yaml
jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.1
```
But the latest tag for `nrwl/ci` is `v0.14.0`, so I expect the content below:
```yaml
jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.14.0
```
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Motivation

I am a beginner for NX and Github Actions, and I spent hours to debug the ci bug
<img width="1069" alt="image" src="https://github.com/nrwl/nx/assets/20757983/e36df88a-a97c-41df-8e2d-b381aed86bc0">
 As you can see [here](https://github.com/acfasj/ieie/actions/runs/6968077894/job/18961228232), the pipeline failed because of incorrect packageJson file path
<img width="1430" alt="image" src="https://github.com/nrwl/nx/assets/20757983/685503c2-02c1-4e10-a15b-ed37daa4ba4c">

After searching for a while, I realised it may related to https://github.com/nrwl/ci/pull/54 (I dont know it is true or not, correct me if wrong) , which was already fixed in the latest `nrwl/ci`, so I change the `nx-cloud-main.yml` to `v0.14.0` and the pipeline success

## Suggested Implementation

see https://github.com/nrwl/nx/blob/6e7141b22c63168c98c6b827d0ed5cc2e98fc165/packages/workspace/src/generators/ci-workflow/files/github/.github/workflows/__workflowFileName__.yml__tmpl__#L17
bump the version from v0.13.1 to 0.14.0
