### ISSUE TITLE
 nx show projects --affected --count and --has-changes flags

### ISSUE THREAD

**Issue by mklueh** [nrwl/nx#20447]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
New arguments for the `nx show projects --affected`  command to quickly check for the number of changed projects or even better, if any project has changes with a boolean return value.

## Motivation
This way, one could quickly disable the entire GitHub Action on the Job level without parsing the result, if none of the projects are affected and skip all the install steps, which are unnecessary.

```
jobs:
  my-job:
    if: $(nx show --affected --has-changes)
    steps:
```

or

```
jobs:
  my-job:
    if: $(nx show --affected --count) == 0
    steps:
```
