### ISSUE TITLE
nx affected --base=main~N ONLY not work in Github Action Runner

### ISSUE THREAD

**Issue by delai** [nrwl/nx#21515]
### Current Behavior

<img width="787" alt="image" src="https://github.com/nrwl/nx/assets/1296212/5256b69f-a79d-4fbf-b70d-bf33477a4c2f">

** Run this command in local Mac is OK, with the same node, pnpm, nx version **

### Expected Behavior

Running the affected command without an error, like the [doc](https://nx.dev/nx-api/nx/documents/affected) said
```
npx nx affected -t lint --base=main~1 --head=HEAD
```

### Steps to Reproduce

This is our github action yaml

``` YAML
name: eslint-delta

env:
  APP_NAME: 'fe-ditto'

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.vue'
      - '**.js'
      - '.github/workflows/eslint-delta.yml'
  push:
    branches:
      - main
      - runner*
    tags:
      - v*
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.vue'
      - '**.js'
      - '.github/workflows/eslint-delta.yml'
jobs:
  build:
    name: Eslint
    runs-on: [self-hosted, online, cloud]
    steps:
      - name: Build For Commit ==> ${{ github.event.head_commit.message }}
        run: |
          node -v
          pnpm -v

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts && npx nx --version

      - name: ESLint
        run: |
          npx nx affected -t lint --base=${{env.BASE}} --head=HEAD
        # if github.event.pull_request.base.sha is empty BASE is the last commit (PR squash merge)
        env:
          BASE: ${{ github.event.pull_request.base.sha  || 'main~1'}}
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : linux-x64
   pnpm   : 8.11.0
   
   nx                 : 17.2.6
   @nx/js             : 17.2.6
   @nx/jest           : 17.2.6
   @nx/linter         : 17.2.6
   @nx/eslint         : 17.2.6
   @nx/workspace      : 17.2.6
   @nx/devkit         : 17.2.6
   @nx/eslint-plugin  : 17.2.6
   @nrwl/tao          : 17.2.6
   @nx/vite           : 17.2.6
   @nx/web            : 17.2.6
   typescript         : 5.3.3
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)
