### ISSUE TITLE
Nx Cloud Agents Cache Restore Error

### ISSUE THREAD

**Issue by cyrus-za** [nrwl/nx#22242]
### Current Behavior

I am using nx-cloud with a custom agent. It passes just fine, but the post-cache step fails

### Expected Behavior

I expect cache-restore step to succeed

### Steps to Reproduce

I can't do a repro right now. But the logs point to tailwind issues.

### Nx Report

```shell
N/A
```

### Failure Logs

```shell
Starting logs...
/tmp/3456827675:5281
  const error = new ConnectError(message !== null && message !== void 0 ? message : "", code, metadata);
                ^

_ConnectError: [unknown] creating tarball: opening file node_modules/tailwind: open node_modules/tailwind: no such file or directory
    at errorFromJson (/tmp/3456827675:5281:17)
    at next (/tmp/3456827675:5643:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.unary (/tmp/3456827675:5612:14)
    at async Object.store (/tmp/3456827675:5070:22) {
  rawMessage: 'creating tarball: opening file node_modules/tailwind: open node_modules/tailwind: no such file or directory',
  code: 2,
  metadata: _Headers [Headers] {
    [Symbol(headers list)]: _HeadersList {
      cookies: null,
      [Symbol(headers map)]: Map(4) {
        'accept-encoding' => { name: 'accept-encoding', value: 'gzip' },
        'content-length' => { name: 'content-length', value: '138' },
        'content-type' => { name: 'content-type', value: 'application/json' },
        'date' => { name: 'date', value: 'Fri, 08 Mar 2024 17:48:59 GMT' }
      },
      [Symbol(headers map sorted)]: null
    },
    [Symbol(guard)]: 'none'
  },
  details: [],
  cause: undefined
}

Node.js v20.9.0
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

```yaml
# agent.yaml
launch-templates:
  linux-medium:
    resource-class: "docker_linux_amd64/medium+"
    image: "ubuntu22.04-node20.9-v3"
    env:
      SELECTED_PM: "pnpm"
      NPM_CONFIG_PREFIX: "/home/workflows/.npm-global"
    init-steps:
      - name: Checkout
        uses: "nrwl/nx-cloud-workflows/v3.1/workflow-steps/checkout/main.yaml"
      - name: Cache restore
        uses: "nrwl/nx-cloud-workflows/v3.1/workflow-steps/cache/main.yaml"
        env:
          KEY: pnpm-lock.yaml
          PATHS: |
            node_modules
            ~/.pnpm-store
          BASE_BRANCH: "main"

      - name: Install pnpm
        script: |
          npm install -g @pnpm/exe@8.7.4

      - name: pnpm Install
        uses: "nrwl/nx-cloud-workflows/v3.1/workflow-steps/install-node-modules/main.yaml"
```
