### ISSUE TITLE
Broken Nx Agent Setup in GitHub Actions' CI Workflow When Using PNPM.

### ISSUE THREAD

**Issue by KerickHowlett** [nrwl/nx#22290]
### Current Behavior

The `ci-workflow` schematic generator from `@nx/workspace` contains a breaking mistake in one of its GitHub Actions template.

What you see in the snippet at the bottom of this post is how the workflow is generated by `@nx/workspace` with no changes made to it whatsoever. As it stands right now, the workflow breaks immediately upon hitting that step with a `pnpm: command not found` error.

The reasons is because this step is placed right behind the `pnpm/actions-setup` step, where `pnpm` is actually installed and configured.

```yaml
name: CI

on:
    push:
        branches:
            - master
    pull_request:

permissions:
    actions: read
    contents: read

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # Connect your workspace on nx.app and uncomment this to enable task distribution.
            # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "build" targets have been requested
            # - run: pnpm exec nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="build"

            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            # Cache node_modules
            - uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: 'pnpm'
            - run: pnpm install --frozen-lockfile
            - uses: nrwl/nx-set-shas@v4

            - run: pnpm exec nx-cloud record -- nx format:check
            - run: pnpm exec nx affected -t lint test build
```

### Expected Behavior

Obviously, the expected behavior is for the schematic generator to produce a GitHub Actions file that doesn't break when it attempts to connect to Nx Cloud.

### Steps to Reproduce

No need for me to fork `nrwl/nx-examples` for this.

Since the aforementioned repo already has `@nx/workspace` installed, all you have to do is use the plugin's `ci-workflow` generator to produce a GitHub Actions workflow.

You can then use [`act`](https://github.com/nektos/act) to run it locally. _(Just note that `act` breaks whenever it attempts to execute `nrwl/nx-set-shas@v3` due to it being a bit behind on GitHub's new way of handling inputs.)_

Or you can just run the CI workflow like normal.

### Nx Report

```shell
Node   : 21.6.2
OS     : linux-x64
pnpm   : 8.15.4

nx (global)        : 18.0.5
nx                 : 18.0.8
@nx/js             : 18.0.8
@nx/jest           : 18.0.8
@nx/eslint         : 18.0.8
@nx/workspace      : 18.0.8
@nx/angular        : 18.0.8
@nx/eslint-plugin  : 18.0.8
@nx/nest           : 18.0.8
@nx/node           : 18.0.8
@nx/react          : 18.0.8
@nrwl/tao          : 18.0.8
@nx/vite           : 18.0.8
@nx/web            : 18.0.8
@nx/webpack        : 18.0.8
typescript         : 5.3.3
---------------------------------------
Community plugins:
@ngneat/spectator : 17.0.0
@ngrx/operators   : 17.1.1
@ngrx/signals     : 17.1.1
ng-mocks          : 14.12.1
ngxtension        : 2.1.0
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)
