### ISSUE TITLE
GitHub Actions Missing Condition?

### ISSUE THREAD

**Issue by marc-wilson** [nrwl/nx#22584]
### Documentation issue

- [ ] Reporting a typo
- [X] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?
CI GitHub Actions Documentation

Enter the URL or documentation section here.
https://nx.dev/ci/recipes/set-up/monorepo-ci-github-actions

### Additional context or description

Provide any additional details here as needed.

The documentation offers this code snippet of how to work with GitHub Actions:
```
name: CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main
  pull_request:

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      # This line enables distribution
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"
      - run: npm ci

      - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main

      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t lint test build e2e-ci

```

This all works as expected in a PR branch. However, once you complete/merge the PR into main, this CI is triggered again and fails on this step:

```
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
```

Does this step only need to run in a PR branch and not in main? Otherwise, this fails with the below error:
<img width="513" alt="image" src="https://github.com/nrwl/nx/assets/19480392/ec14837a-f855-473b-9250-3cb2a489e0a5">

Should it really be:
```
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
        if: ${{ github.event_name == 'pull_request' }}
```
