### ISSUE TITLE
Add to docs that a GitHub token is required for automating GitHub releases

### ISSUE THREAD

**Issue by leonk** [nrwl/nx#22857]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipes/nx-release/automate-github-releases

### Additional context or description

A token is required for nx to push the release to GitHub.  I worked out that this could be done by setting the default `GITHUB_TOKEN` (which is available when creating the release directly from a GitHub action) as an environment variable for the step that runs `nx release`.  E.g. 
```
      - name: Run Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx nx release
```
But for those running `nx release` locally, they will want to set the `GITHUB_TOKEN` to a PAT.  It would be good to show both examples.
