### ISSUE TITLE
[nx release] Add support for gitlab releases

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#22985]
### Current Behavior

`nx release` command supports the creation of releases in GitHub.com

### Expected Behavior

Like GitHub.com, gitlab support would be appreciated

### Steps to Reproduce

N/A

### Nx Report

```shell
N/A
```

### Package Manager Version

N/A

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jasus** [comment]
@JamesHenry I can help here as we discussed in the other post.

Thanks

**Comment by AaronLayton** [comment]
I'm not fussed about a release just yet, but just trying to get up an `nx release` pipeline job setup that commits back in the changelogs and the updated tags. Any legend want to share their current `.gitlab-ci.yml`

**Comment by JamesHenry** [comment]
Working on it! 

![Image](https://github.com/user-attachments/assets/67e9f54a-ec03-40ee-afa7-7dc7ffbc1f04)

**Comment by AaronLayton** [comment]
> I'm not fussed about a release just yet, but just trying to get up an `nx release` pipeline job setup that commits back in the changelogs and the updated tags. Any legend want to share their current `.gitlab-ci.yml` 🙏

For anyone looking back at this, I managed to get Private NPM Gitlab packages being deployed with the below (setup a Project Access Token with API access for `$PROJECT_TOKEN`

```yaml

stages:
  - test
  - release
  - notify

variables:
  NODE_VERSION: 22
  CI: 'true'
  GIT_DEPTH: 0  # Needed for proper version determination
  GIT_USER_NAME: 'GitLab CI'
  GIT_USER_EMAIL: 'ci@gitlab.com'
  NX_NO_CLOUD: true

# CI Proxy due to new Docker pull limits (node version setup in a variable as I use this as a template across multiple projects)
image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/node:${NODE_VERSION}

# Common cache configuration to reuse
.npm_cache: &npm_cache
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - .nx/cache

# Actually publish the NPM packages
release-packages:
  stage: release
  <<: *npm_cache
  only:
    - master
  before_script:
    - git config --global user.email "${GIT_USER_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME}"
    - git remote set-url origin https://oauth2:${PROJECT_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" > ~/.npmrc
  script:
    - npm ci --legacy-peer-deps --prefer-offline --no-audit
    # Use the original approach that was working
    - npx nx release --yes
    # Push changes with tags (had to do this as it doesn't commit in when using nx.json with commit / tag set to true
    - git push origin HEAD:master --follow-tags --no-verify
  artifacts:
    paths:
      - packages/*/CHANGELOG.md
      - packages/*/*.tgz
    expire_in: 1 hour

# Notify Slack about stable releases (reads Git history to see if there was a `chore` and then reads the changelogs to post to Slack)
notify-slack:
  stage: notify
  only:
    - master
  needs: [release-packages]
  script:
    - npm ci --legacy-peer-deps --prefer-offline --no-audit
    - node tools/scripts/notify-release.js
```
