### ISSUE TITLE
nx-cloud complete-ci-run doesn't close agents

### ISSUE THREAD

**Issue by aramfe** [nrwl/nx#26590]
### Current Behavior

Sometimes agents are not shutdown and start hanging, even though the main job successfully completed with: 

```
      - name: "Complete nx run and stop all nx agents"
        if: ${{ always() }}
        run: npx nx-cloud complete-ci-run
```

### Expected Behavior

Agents should be closed after `npx nx-cloud complete-ci-run` was run

### Steps to Reproduce

This is my workflow definition: 

```
name: NX-Deployment

#disable workflow
# on:
#  push:
#    branches-ignore: "*"

# WORKFLOW TRIGGER
on: push

# CONCURRENCY
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: ${{ !contains(github.ref_name, 'master')}}

permissions:
  actions: read
  contents: read

# GLOBAL ENVIRONMENT VARIABLES
env:
  AWS_XRAY_CONTEXT_MISSING: "LOG_ERROR"
  AWS_XRAY_LOG_LEVEL: "SILENT"
  AWS_RETRY_MODE: standard
  AWS_MAX_ATTEMPTS: 10
  NODE_OPTIONS: --max-old-space-size=6144
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_CLOUD_DTE_V2: true

jobs:
  main-staging:
    if: github.ref_name != 'master'
    runs-on: buildjet-2vcpu-ubuntu-2204
    name: Main Staging
    timeout-minutes: 60
    env:
      NX_CI_EXECUTION_ENV: staging_${{ github.run_number }}_${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      # Setup
      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Setup aws credentials"
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: "Setup Amazon ECR credentials"
        uses: aws-actions/amazon-ecr-login@v2
      - name: "Start nx cloud cluster"
        run: >
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION=eu-central-1
          INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN}}
          npx nx-cloud start-ci-run --with-env-vars="AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION,INPUT_GITHUB_TOKEN" --require-explicit-completion --stop-agents-on-failure=false
      - name: "Install node dependencies"
        run: yarn install --immutable
      - name: "Install playwright components for application tests"
        run: cd application-tests/sde && yarn playwright install
      - name: "Run build and deployment"
        run: >
          INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN}}
          yarn nx run-many -t validate-neo4j deploy-deployment deploy-backoffice deploy-werk --args="--deployment=staging" --parallel 1
      - name: "Run seo script, backoffice integration tests and application tests"
        uses: nick-fields/retry@v3 # GitHub based retries for flaky application test handling
        with:
          timeout_minutes: 40
          max_attempts: 2
          command: >
            INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN}}
            yarn nx run-many -t deploy-seo create-default-users e2e-ci-without-args backoffice-integration-tests --args="--deployment=staging" --parallel 1
      - name: "Complete nx run and stop all nx agents"
        if: ${{ always() }}
        run: npx nx-cloud complete-ci-run
      - name: "Complete nx run and stop all nx agents"
        if: ${{ always() }}
        run: npx nx-cloud stop-all-agents

  agents-staging:
    if: github.ref_name != 'master'
    runs-on: buildjet-2vcpu-ubuntu-2204
    name: Agent Staging
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3, 4, 5, 6, 7]
    env:
      NX_CI_EXECUTION_ENV: staging_${{ github.run_number }}_${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      # Setup
      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Setup aws credentials"
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: "Setup Amazon ECR credentials"
        uses: aws-actions/amazon-ecr-login@v2
      - name: "Install node dependencies"
        run: yarn install --immutable
      - name: "Install playwright components for application tests"
        run: cd application-tests/sde && yarn playwright install
      - name: "Start nx Agent ${{ matrix.agent }}"
        run: INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN}} npx nx-cloud start-agent
```

### Nx Report

```shell
Node   : 18.19.0
OS     : linux-x64
yarn   : 4.3.0

nx              : 19.3.0
@nx/js          : 19.3.0
@nx/jest        : 19.3.0
@nx/linter      : 19.3.0
@nx/eslint      : 19.3.0
@nx/workspace   : 19.3.0
@nx/devkit      : 19.3.0
@nx/playwright  : 19.3.0
@nrwl/tao       : 19.3.0
typescript      : 4.9.4
---------------------------------------
Registered Plugins:
@nxrocks/nx-spring-boot
@nx/playwright/plugin
---------------------------------------
Community plugins:
@nx-tools/nx-container  : 6.0.1
@nxrocks/nx-spring-boot : 10.0.2
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Happens sporadically without any reason.
