### ISSUE TITLE
nx@npm:x.x.x [377db] couldn't be built successfully (exit code 129)

### ISSUE THREAD

**Issue by mhp-borisbojic** [nrwl/nx#27397]
### Current Behavior

Since the latest version with NX (18 and 19), our yarn 4 install command randomly fails with error 129 in GitHub Action CI/CD workflow and AWS Codebuild CI/CD. After retrying it 1-2 times, it works.

The reported log is also empty, e.g. /tmp/xfs-5678ef46/build.log

This only happens within our CI/CD - locally on our working machines (macOS) we never see this issue.

### Expected Behavior

Yarn install should **always** work and not fail randomly with this error (and no further logs).

### Steps to Reproduce

1. Since this is a customer project, we can't give you any access to our repository or CD/CD.

### Nx Report

```shell
Node   : 20.15.0
OS     : darwin-arm64
yarn   : 4.4.0

nx (global)        : 19.3.2
nx                 : 19.4.4
@nx/js             : 19.4.4
@nx/jest           : 19.4.4
@nx/linter         : 19.4.4
@nx/eslint         : 19.4.4
@nx/workspace      : 19.4.4
@nrwl/workspace    : 19.3.0
@nx/angular        : 19.4.4
@nx/devkit         : 19.4.4
@nrwl/devkit       : 19.3.0
@nx/eslint-plugin  : 19.4.4
@nx/nest           : 19.4.4
@nx/node           : 19.4.4
@nx/playwright     : 19.4.4
@nrwl/tao          : 19.3.0
@nx/web            : 19.4.4
@nx/webpack        : 19.4.4
typescript         : 5.5.4
---------------------------------------
Community plugins:
@auth0/auth0-angular       : 2.2.3
@ng-bootstrap/ng-bootstrap : 17.0.0
@ngxs/store                : 18.1.1
@nx-extend/terraform       : 6.0.5
ng-mocks                   : 14.13.0
nx-stylelint               : 17.1.5
---------------------------------------
```

### Failure Logs

```shell
Run yarn install
➤ YN0000: · Yarn 4.4.0
➤ YN0000: ┌ Resolution step
Resolution step
➤ YN0000: └ Completed in 0s 524ms
➤ YN0000: ┌ Post-resolution validation
Post-resolution validation
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
Fetch step
➤ YN0000: └ Completed in 24s 439ms
➤ YN0000: ┌ Link step
Link step
➤ YN0009: nx@npm:19.3.0 [377db] couldn't be built successfully (exit code 129, logs can be found here: /tmp/xfs-5678ef46/build.log)
/tmp/xfs-5678ef46/build.log
➤ YN0000: └ Completed in 33s 418ms
➤ YN0000: · Failed with errors in 58s 832ms
Error: Process completed with exit code 1.
```

### Package Manager Version

yarn 4.4.0

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by btisdall** [comment]
Hi, we're also seeing this in my team. I can share this GitHub Actions snippet in case it's helpful (nothing special going on):

```
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set specific Node version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Set Directory as Safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        shell: bash
      - name: Restore cached npm dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: npm-dependencies-${{ hashFiles('yarn.lock') }}
      - name: Install yarn
        run: corepack enable
      - name: Install packages
        run: yarn install --immutable
```

Build node is an AWS CodeBuild `BUILD_GENERAL1_MEDIUM` and we're nowhere near running out of memory, CPU or disk during the process.

I'm not certain this is an nx issue we haven't changed anything on that side recently, however neither have we made any other changes to dependencies in the project – the problem has seemingly come out of nowhere.

**Comment by mhp-borisbojic** [comment]
I've probably found the issue ... the package `@nx-extend/terraform` enforced the "old" NX versions of e.g. nx@npm, so our yarn.lock ended up having an old a new version of nx@npm.

Since I've removed `@nx-extend/terraform`, this error doesn't happen anymore. I will still have a look on this for a week, but if it doesn't occur anymore, it's probably resolved.

**Comment by btisdall** [comment]
Thanks @mhp-borisbojic . We weren't using that library but `nx report` did reveal some inconsistencies between `nx` and bunch of `@nx/*` packages. Even though the discrepancy had existed for some time before we started to see the failures, addressing it with `nx migrate` is the thing that has apparently fixed it 🤷‍♀️ .

**Comment by FrozenPandaz** [comment]
Seems like this issue has been fixed by aligning Nx package versions. Please keep those aligned with `nx migrate` :+1:

**Comment by mhp-borisbojic** [comment]
> Seems like this issue has been fixed by aligning Nx package versions. Please keep those aligned with `nx migrate` 👍

Actually, yes and no. `nx migrate` didn't help since there was no new version of `@nx-extend/terraform` - the only solution for the moment was to remove it completely.

**Comment by umermughal** [comment]
I was facing a similar issue today, I'm using yarn 4 and it was failing with this error
```
 YN0009: nx@npm:19.6.4 [b49c3] couldn't be built successfully (exit code 129, logs can be found here: /tmp/xfs-1bc0266f/build.log)
/tmp/xfs-1bc0266f/build.log

```
and after checking my package.json, I realized that my @nx/storybook plugin was using version 19.x, while my Nx version was 18. Downgrading @nx/storybook to version 18 resolved the issue. Thanks @mhp-borisbojic for sharing the hint 🙏

**Comment by samijaber** [comment]
Came here to comment that we are actively encountering this issue, yet have no NX version conflicts.

The only Nx packages we install are:

- `nx-cloud@npm:19.0.0`
- `nx@npm:19.6.5`

We do not use any other nx package. running `nx report` does not outline any issues, nor does `nx migrate` make any changes.

We keep encountering the `nx@npm:x.x.x [377db] couldn't be built successfully (exit code 129)` issue.

**Comment by umermughal** [comment]
> Came here to comment that we are actively encountering this issue, yet have no NX version conflicts.
> 
> The only Nx packages we install are:
> 
> * `nx-cloud@npm:19.0.0`
> * `nx@npm:19.6.5`
> 
> We do not use any other nx package. running `nx report` does not outline any issues, nor does `nx migrate` make any changes.
> 
> We keep encountering the `nx@npm:x.x.x [377db] couldn't be built successfully (exit code 129)` issue.

You have minor version issue as you can see nx @ 19.6.5 and cloud dependency is 19.0.0 so to make it work you have to use same version for all nx dependencies.

**Comment by samijaber** [comment]
@umermughal no, `nx-cloud`'s latest version is `19.1.0`. They don't have the exact same version numbers.

https://www.npmjs.com/package/nx-cloud?activeTab=versions
https://www.npmjs.com/package/nx?activeTab=versions

**Comment by samijaber** [comment]
UPDATE: in my case, I've given up on trying to understand the issue. My workaround is to disable `nx`'s build step altogether. This doesn't seem to negatively impact my usage of `nx` in CI (or locally). Not sure what this build step is actually doing.

I do so by adding the following to `package.json` (I am on yarn v3):

```json
"dependenciesMeta": {
    "nx": {
      "built": false
    },
    "nx-cloud": {
      "built": false
    }
  }
```

**Comment by mklueh** [comment]
I was facing random exceptions in GitHub Actions with Yarn Berry 4.5 as well.

On some branches it happened with totally unrelated changes, not even from the affected application and on others it seemed to work.

First I thought it was related to the caching config


```
      - uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
          check-latest: false
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock' //adding this did not help
```

and this has also no effect

```
"dependenciesMeta": {
    "nx": {
      "built": false
    },
    "nx-cloud": {
      "built": false
    }
  }
```

Would appreciate any help
