### ISSUE TITLE
NX RELEASE pushing in protected branch - GitHub

### ISSUE THREAD

**Issue by jasus** [nrwl/nx#28141]
### Current Behavior

I'm trying to apply NX release in a workflow in github actions but I have the rule to protect the main branch.

Even if I put in the rule that allow me to force push or by pass to create a pull request before merge is throwing the same error:

```
 NX   Staging changed files with git
 NX   Committing changes with git
 NX   Tagging commit with git
 NX   Pushing to git remote
 NX   Unexpected git push error: remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: 
remote: - 3 of 3 required status checks are expected.        
To https://github.com/XXXXX
 ! [remote rejected] main -> main (protected branch hook declined)
 ! [remote rejected] @YYYY/XXX/v0.2.1 -> @YYYY/XXX/v0.2.1 (atomic transaction failed)
error: failed to push some refs to 'https://github.com/xxxxx'
Pass --verbose to see the stacktrace.
Error: Process completed with exit code 1.
```

### Expected Behavior

Be able to create the release in the pipeline even with protected branch and rules

### Steps to Reproduce

This is my workflow and I read that in checkout I should put the token of the user with admin rights

Also I put the same for the nx release command

```
name: Nx release workflow

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: write

jobs:
  release:
    name: Nx Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      
      - uses: nrwl/nx-set-shas@v4
      - run: |
          git config --global user.email "my_user@email.com"
          git config --global user.name "my_user"
      - run: npx nx release --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
```

Github rules

![image](https://github.com/user-attachments/assets/e3556c5e-9d0a-4616-be9b-37fb3367726d)
![image](https://github.com/user-attachments/assets/d285e7ad-3fe9-4423-a510-d2008bc681ef)
![image](https://github.com/user-attachments/assets/10053f58-71ed-4a86-90ae-e02004d441cb)

### Nx Report

```shell
Node           : 18.16.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 9.5.1

nx                 : 19.6.4
@nx/js             : 19.6.4
@nx/jest           : 19.6.4
@nx/linter         : 19.6.4
@nx/eslint         : 19.6.4
@nx/workspace      : 19.6.4
@nx/cypress        : 19.6.4
@nx/devkit         : 19.6.4
@nx/eslint-plugin  : 19.6.4
@nx/react          : 19.6.4
@nx/storybook      : 19.6.4
@nrwl/tao          : 19.6.4
@nx/vite           : 19.6.4
@nx/web            : 19.6.4
typescript         : 5.5.2
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/storybook/plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)
