### ISSUE TITLE
NX cloud issue with pnpm

### ISSUE THREAD

**Issue by el-davo** [nrwl/nx#29091]
### Current Behavior

I have the following github actions file. If anyone can help me figure out why pnpm is failing or where the `pnpm install --frozen-lockfile` command is even coming from, as it is not in my github actions file

```yaml
name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-small-js" --stop-agents-after="build"
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
  
      - run: pnpm i
      - uses: nrwl/nx-set-shas@v4

      - run: npm run nx affected -t lint test build

```

Whenever I make a change I get this error on the nx cloud interface. Im not sure where this step is or why it fails. Even changing the package manager from pnpm to npm or yarn does not fix the issue as it always tries to run this `pnpm install --frozen-lockfile` command for some reason, if anyone can help I would be most grateful.

![Image](https://github.com/user-attachments/assets/0548f434-7c38-42c3-9aec-56e7c37e4cd6)

### Expected Behavior

CI runs should pass

### Steps to Reproduce

1.

### Nx Report

```shell
Node           : 19.9.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.14.2

nx                 : 20.1.2
@nx/js             : 20.1.2
@nx/jest           : 20.1.2
@nx/eslint         : 20.1.2
@nx/workspace      : 20.1.2
@nx/angular        : 20.1.2
@nx/devkit         : 20.1.2
@nx/eslint-plugin  : 20.1.2
@nx/playwright     : 20.1.2
@nx/vite           : 20.1.2
@nx/web            : 20.1.2
@nx/webpack        : 20.1.2
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
```

### Failure Logs

```shell
Installing dependencies using pnpm
2      Running command: pnpm install --frozen-lockfile
3    
4     WARN  Ignoring not compatible lockfile at /home/workflows/workspace/pnpm-lock.yaml
5     ERR_PNPM_NO_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is absent
6    
7    Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"
8    node:child_process:965
9        throw err;
10       ^
11   
12   Error: Command failed: pnpm install --frozen-lockfile
13       at checkExecSyncError (node:child_process:890:11)
14       at execSync (node:child_process:962:15)
15       at Object.<anonymous> (/tmp/2235265147:9:3)
16       at Module._compile (node:internal/modules/cjs/loader:1376:14)
17       at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
18       at Module.load (node:internal/modules/cjs/loader:1207:32)
19       at Module._load (node:internal/modules/cjs/loader:1023:12)
20       at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
21       at node:internal/main/run_main_module:28:49 {
22     status: 1,
23     signal: null,
24     output: [ null, null, null ],
25     pid: 95,
26     stdout: null,
27     stderr: null
28   }
29   
30   Node.js v20.11.1
```

### Package Manager Version

pnpm 9.14.2

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by MoritzMeinhardt** [comment]
Hi there, 
Same issue. I am currently setting up a new project, trying nx cloud and pnpm.  So far mainly following the docs, I did not try any edge cases from my pov.

`1    Installing dependencies using pnpm
2      Running command: pnpm install --frozen-lockfile
3    
4     WARN  Ignoring not compatible lockfile at /home/workflows/workspace/pnpm-lock.yaml
5     ERR_PNPM_NO_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is absent
6    
7    Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"
8    node:child_process:965
9        throw err;
10       ^
11   
12   Error: Command failed: pnpm install --frozen-lockfile
13       at checkExecSyncError (node:child_process:890:11)
14       at execSync (node:child_process:962:15)
15       at Object.<anonymous> (/tmp/4243775239:9:3)
16       at Module._compile (node:internal/modules/cjs/loader:1376:14)
17       at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
18       at Module.load (node:internal/modules/cjs/loader:1207:32)
19       at Module._load (node:internal/modules/cjs/loader:1023:12)
20       at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
21       at node:internal/main/run_main_module:28:49 {
22     status: 1,
23     signal: null,
24     output: [ null, null, null ],
25     pid: 109,
26     stdout: null,
27     stderr: null
28   }
29   
30   Node.js v20.11.1`

My pnpm version is 9.15.0.

![Image](https://github.com/user-attachments/assets/66a35be5-ea29-4259-81b2-aa5a4240bb5c)

**Comment by MoritzMeinhardt** [comment]
I found the issue in our setup. 
We switched from `npm` to `pnpm` but we did not update our execution commands as described in here: 
https://nx.dev/ci/features/distribute-task-execution?utm_source=nx.app

 

> - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"
> - run: pnpm exec nx affected -t lint test build

**Comment by MoritzMeinhardt** [comment]
I fixed it by downgrading to `pnpm v8`.

**Comment by el-davo** [comment]
@MoritzMeinhardt How did you downgrade to version 8?

I tried this but it still gives the same error

```yaml
 - uses: pnpm/action-setup@v4
        with:
          version: 8
```
