### ISSUE TITLE
NX   Cannot read properties of undefined (reading 'startsWith') versel build

### ISSUE THREAD

**Issue by ladraniamine** [nrwl/nx#30761]
### Current Behavior

getting this issue when i try to build the project on vercel

### Expected Behavior

i expect the build of three apps [admin, agent, client]

### Steps to Reproduce

1. im trying to deploy the three apps on vercel 

my structure
frontend/
├── apps/
│   ├── admin/
│   │   ├── project.json    # Admin config
│   │   └── ...             # App source files
│   ├── agent/
│   │   ├── project.json    # Agent config
│   │   └── ...             
│   └── client/
│       ├── project.json    # Client config
│       └── ...             
├── .github/
│   └── workflows/
│       └── deploy.yml      # GitHub Actions workflow
├── pnpm-workspace.yaml     # PNPM workspace config
└── package.json

project.json
```json
{
  "name": "admin",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "admin/src",
  "projectType": "application",
  "tags": [],
  "// targets": "to see all targets run: nx show project admin --web",
  "targets": {
    "build": {
      "executor": "@nx/vite:build",
      "options": {
        "outputPath": "dist/apps/admin",
        "configFile": "apps/admin/vite.config.ts",
        "baseHref": "/admin/",
        "assets": [
          "apps/admin/src/favicon.ico",
          "apps/admin/src/assets",
          {
            "input": "libs/Assets/src/lib",
            "glob": "**/*",
            "output": "assets"
          }
        ]
      },
      "configurations": {
        "production": {
          "mode": "production",
          "sourcemap": false,
          "emptyOutDir": true,
          "fileReplacements": [
            {
              "replace": "apps/admin/src/environments/environment.ts",
              "with": "apps/admin/src/environments/environment.prod.ts"
            }
          ]
        }
      }
    },
    "serve": {
      "executor": "@nx/vite:dev-server",
      "options": {
        "buildTarget": "admin:build"
      }
    },
    "preview": {
      "executor": "@nx/vite:preview-server",
      "options": {
        "buildTarget": "admin:build"
      }
    },
    "deploy": {
      "executor": "nx:run-commands",
      "options": {
        "command": "vercel deploy --prebuilt --prod --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID",
        "cwd": "dist/apps/admin"
      }
    }
  }
}

```
vite.config
```ts
/// <reference types='vitest' />
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { nxViteTsPaths } from "@nx/vite/plugins/nx-tsconfig-paths.plugin";
import { nxCopyAssetsPlugin } from "@nx/vite/plugins/nx-copy-assets.plugin";
import path from "path";

export default defineConfig(({ mode }) => ({
  root: __dirname,
  cacheDir: "../../node_modules/.vite/admin",
  assetsInclude: ["**/*.md", "**/*.svg", "**/*.png", "**/*.jpg", "**/*.jpeg"],
  define: {
    "process.env.NODE_ENV": JSON.stringify(mode),
  },
  server: {
    port: 4200,
    host: "localhost",
  },
  preview: {
    port: 4300,
    host: "localhost",
  },
  plugins: [react(), nxViteTsPaths(), nxCopyAssetsPlugin(["*.md", "*.csv", "*.pdf"])],
  resolve: {
    alias: {
      src: path.resolve(__dirname, "./src"),
      "@Assets": path.resolve(__dirname, "../../libs/Assets/src/lib"),
      "@UISELTYPEL": path.resolve(
        __dirname,
        "../../libs/UISELTYPEL/src/lib/Components"
      ),
      "@Utils": path.resolve(__dirname, "../../libs/Utils/src/lib"),
    },
  },
  build: {
    outDir: "../../dist/apps/admin",
    emptyOutDir: true,
    manifest: true,
    reportCompressedSize: true,
    commonjsOptions: {
      transformMixedEsModules: true,
    },
    rollupOptions: {
      output: {
        assetFileNames: `assets/[name]-[hash][extname]`,
        entryFileNames: `assets/[name]-[hash].js`,
        chunkFileNames: `assets/[name]-[hash].js`,
      },
    },
  },
  base: "/admin/",
}));
```
deploy.yaml
```yaml
name: Deploy to Vercel

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ["admin", "agent", "client"]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest

      - name: Build app
        run: pnpm nx run ${{ matrix.app }}:build:production --verbose
          ls -R dist/apps/${{ matrix.app }}

      - name: Deploy to Vercel
        run: |
          vercel deploy \
            --prebuilt \
            --prod \
            --token $VERCEL_TOKEN \
            --scope $VERCEL_ORG_ID \
            --project $VERCEL_PROJECT_ID \
            --local-config ../../vercel.json \
            --yes \
            dist/apps/${{ matrix.app }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets[format('{0}_VERCEL_PROJECT_ID', matrix.app)] }}
```

### Nx Report

```shell
Node           : 22.13.0
OS             : linux-x64
Native Target  : x86_64-linux
pnpm           : 9.6.0

nx (global)        : 20.8.0
nx                 : 20.8.0
@nx/js             : 20.8.0
@nx/eslint         : 20.8.0
@nx/workspace      : 20.8.0
@nx/eslint-plugin  : 20.8.0
@nx/react          : 20.8.0
@nx/vite           : 20.8.0
@nx/web            : 20.8.0
typescript         : 5.7.3
---------------------------------------
Registered Plugins:
@nx/react/router-plugin
@nx/eslint/plugin
@nx/vite/plugin
---------------------------------------
Cache Usage: 23.71 MB / 45.69 GB
```

### Failure Logs

```shell
NX   Cannot read properties of undefined (reading 'startsWith')
Pass --verbose to see the stacktrace.
 NX   Running target build for project admin failed
Failed tasks:
- admin:build
Hint: run the command with --verbose for more details.
Error: Command "npx nx build admin" exited with 1
```

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)
