### ISSUE TITLE
EAS workflow builds fail when trying to build an Expo app

### ISSUE THREAD

**Issue by hassankhan** [nrwl/nx#31030]
### Current Behavior

When trying to build an Expo app via an [EAS Workflow](https://docs.expo.dev/eas/workflows/get-started/), I get dependency issues and ultimately a build failure

### Expected Behavior

My Expo app should build on EAS with no extra setup.

### Steps to Reproduce

1. Create an Nx monorepo with an Expo app
2. Set up an EAS workflow to build the app
3. Observe multiple dependency failures 

<details>
<summary>
Sample EAS workflow
</summary>

```yaml
name: Build preview

on:
  push:
    branches:
      - main

jobs:
  # Fingerprint this commit to see what native capabilities it needs
  fingerprint:
    name: Fingerprint
    env:
      EAS_PUBLIC_UPDATE_CHANNEL: ${{ github.ref || 'manual-workflow-trigger' }}
    type: fingerprint

  # Run the EAS update in parallel with the fingerprint, since we'll use it no matter what.
  run_eas_update:
    name: EAS update
    type: update
    params:
      platform: all
      channel: ${{ github.ref || 'manual-workflow-trigger' }}

  # Check if we have an existing Android preview build
  get_android_build:
    name: Check for Android build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      platform: android
      profile: preview

  # Check if we have an existing iOS preview build
  get_ios_build:
    name: Check for iOS build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      platform: ios
      profile: preview

  # If we don't get a build_id from get_android_build, move forward with building from the ground up.
  build_android:
    name: Build Android
    needs: [get_android_build]
    if: ${{ !needs.get_android_build.outputs.build_id }}
    type: build
    env:
      EAS_PUBLIC_UPDATE_CHANNEL: ${{ github.ref || 'manual-workflow-trigger' }}
    params:
      platform: android
      profile: preview

  # If we don't get a build_id from get_ios_build, move forward with building from the ground up.
  build_ios:
    name: Build iOS
    needs: [get_ios_build]
    if: ${{ !needs.get_ios_build.outputs.build_id }}
    type: build
    env:
      EAS_PUBLIC_UPDATE_CHANNEL: ${{ github.ref || 'manual-workflow-trigger' }}
    params:
      platform: ios
      profile: preview
```

</details>

### Nx Report

```shell
Node           : 20.17.0
OS             : darwin-arm64
Native Target  : aarch64-macos
bun            : 1.1.27
nx (global)            : 20.0.0
nx                     : 20.3.0
@nx/js                 : 20.3.0
@nx/jest               : 20.3.0
@nx/eslint             : 20.3.0
@nx/workspace          : 20.3.0
@nx/devkit             : 20.3.0
@nx/eslint-plugin      : 20.3.0
@nx/expo               : 20.3.0
@nx/module-federation  : 20.3.0
@nx/next               : 20.3.0
@nx/playwright         : 20.3.0
@nx/react              : 20.3.0
@nx/vite               : 20.3.0
@nx/web                : 20.3.0
@nx/webpack            : 20.3.0
typescript             : 5.6.3
---------------------------------------
Registered Plugins:
@nx/expo/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/next/plugin
@nx/playwright/plugin
```

### Failure Logs

```shell

```

### Operating System

- [x] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Nx used to add an `eas-pre-install.mjs` file to the monorepo previously, this code now seems to have been moved [here](https://github.com/nrwl/nx/blob/master/packages/expo/src/executors/build/build.impl.ts#L121-L165).

I think that this change should be reverted, and the EAS pre-install script should be accessible within the repo for use in EAS Build and EAS Workflow.
