### ISSUE TITLE
Feature Request: nx format:check should provide a workaround for Prettier not supporting format diffing

### ISSUE THREAD

**Issue by jacopolanzoni** [nrwl/nx#4159]
# UPDATE FROM NX TEAM (2024-05-17)

Please read: https://github.com/nrwl/nx/issues/4159#issuecomment-2118165264

---

## Description
As `nx format:check` shows which files fail the format check but not what is actually wrong in them, I would love if the `--verbose` option could actually add that information. At the moment, unless I am doing something wrong, `nx format:check --verbose` has the same output as `nx format:check`.

## Motivation
The command would give more information about what is actually wrong in the file format. 

## Suggested Implementation
I would love if the `--verbose` option could actually add that information.

## Alternate Implementations
As an alternative, I would like even only to see either the line where the check fails, or maybe the broken rule.

**Comment by konrad-garus** [comment]
It's like a slap in the face without ever even telling you _why_. Imagine a compiler telling you "Error, GFY, period".

Please add this.

**Comment by TCModus** [comment]
My entire team is complaining about this, going to have to remove my formatting check from pre-commit hook because it is just confusing everyone.  The --verbose flag should be at minimum spitting out the same output of the format:write command which at least shows the command crawling through the project directories doing the formatting.

FYI for others with this issue it seems like you can run prettier using npm and get the output from running the prettier command directly instead of through Nx.

**Comment by Alspaladin** [comment]
Why it's closed? My project is failing on nx format:check without any message besides the `error Command failed with exit code 1.` and --verbose adds nothing to it

**Comment by eprokofev** [comment]
I don't understand "stale" logic as well. My pipeline also failed at this step without any reason. Verbose is not informative at all.

**Comment by xaphod** [comment]
Yeah, reopen this issue - verbose is broken

**Comment by KlausNie** [comment]
Same here

**Comment by konnic** [comment]
Just ran into the same issue, would like to see this issue being reopened...

**Comment by konnic** [comment]
If it helps anyone, running `nx format:write` solved issue for me.

**Comment by StephenStrickland** [comment]
`nx format:check --verbose` is still broken

**Comment by savvyshell** [comment]
How has this not been addressed , it's running fine locally, failing in CI with no information.

**Comment by savvyshell** [comment]
```
init-commands: |
  npx nx-cloud record -- npx prettier --write .
  npx nx-cloud record -- npx nx format:write
  npx nx-cloud record -- npx prettier --check .
  npx nx-cloud record -- npx nx format:check
```

I added this to my actions.yml file and it seems to do the trick. Rather than rely on `nx format:check`, I hand it over to prettier since it's tied to my eslint configuration and I'd imagine format:check is using part of that anyways. I have it auto format with prettier followed by nx format:write just to be safe before checking with both prettier and nx format. 

It's probably not necessary to use both but just to still make sure NX is some-what happy, I wanted to use their format checker.

Seems to work now, hope we can get a proper solution for this in the future.

**Comment by nhhockeyplayer** [comment]
> angular.json, nx.json, and tsconfig.base.json

That worked for me thanks friend

finally got nxcloud builds in flight

npmjs.org held me down in a user account debilitation locked out from their case logic creating users for emails that they dont even validate... ditched npmjs for github registry and I think this is the trend. sorry npmjs its been real.

nxcloud rocks

**Comment by puf17640** [comment]
why is this closed as completed if it's still a problem?

**Comment by Clean-Cole** [comment]
Our team is having the same issue.

**Comment by kekiel** [comment]
+1 for showing what is wrong with the file(s)

**Comment by dgesteves** [comment]
I am still having this issue with my CI any solution?

**Comment by StefanGreffenius** [comment]
Same issue here, we are missing the detailed error output of prettier

**Comment by PayBas** [comment]
We parse our build logs to collect data on issues. The output of `nx format:check` is less than useless and is impossible to parse since there is nothing identifying the error, except the exit code.
I would at least expect some kind of line (even without the `--verbose` flag) like:
```
NX/Prettier format check error(s) for file(s):
<the file list>
```
But as others have mentioned, actually showing some verbose output is desperately needed.

**Comment by amogower** [comment]
+1 for providing info on failed check please 🙏

**Comment by kodeine** [comment]
bump, please this is needed. 🙏

**Comment by meisterveda** [comment]
Still verbose not working correctly

**Comment by JPedroSMFerreira** [comment]
$ nx format:write

 >  NX   Affected criteria defaulted to --base=develop --head=HEAD

libs\common\ui-sales-components\src\lib\... 477ms
libs\common\ui-sales-components\src\lib\save... 183ms
angular.json 236ms
nx.json 12ms
tsconfig.base.json 49ms

Et voilá!

**Comment by brumargues** [comment]
@JPedroSMFerreira, it worked like a gem!
Thank you

**Comment by exsesx** [comment]
> @JPedroSMFerreira, it worked like a gem!
> 
> 
> 
> But `--verbose` still needs a fix.
> 
> 
> 
> Thank you!

This issue is about the format:check command. It's not a solution if we have to change the command, which is completely changing the logic, by the way.

We could forward args to the prettier command, or you could find a way to print your message before the format:check execution.

It would've been nicer to have a solution developed by the NX team to make it more flexible. I had a complaint from my team that they couldn't figure out why they could not commit their changes because of the output of the format command. We got used to it, though, and adjusted our processes.

**Comment by theonetheycallneo** [comment]
I also noticed that VSCode's auto-save doesn't match `nx format:write`, so we were continuously getting this issue.

**Comment by puf17640** [comment]
you would think a team working on a project this size and importance would recognize such an issue that has been complained about for more than 2 years now... pretty disappointing to not even get any answer from the team on this...

I already tried my luck with fixing this the first time I came here, didn't work well as you see. But I think me having to come here again is a pretty good sign that I should just try again, since nobody will take on this issue apparently.

**Comment by kodeine** [comment]
Maybe its time to open a new ticket?

**Comment by 72gm** [comment]
Can somebody deal with this please... it's a massive pain in the backside... fine locally but failing in CI with no information whatsoever.... 

$8.6M in seed funding at the end of last year so you should have the resources

**Comment by HenrikTusz** [comment]
Same here working, failing in ci but working locally.

**Comment by timonmasberg** [comment]
We experienced the same issue. This is probably related to https://github.com/prettier/prettier/issues/6885

When we investigated this issue, we ran prettier write and checked the diff:

![image](https://user-images.githubusercontent.com/13659466/229368918-d3d7719e-4ac2-4101-ab9b-c467c1cfee28.png)

This is rather strange behavior, I think prettier needs to sort this one out...

**Comment by marc-wilson** [comment]
I am confused as well. I am evaluating Nx and am playing around with their Azure DevOps example [here](https://nx.dev/recipes/ci/monorepo-ci-azure).

The documentation offers this snippet:

```
trigger:
  - main
pr:
  - main

variables:
  CI: 'true'
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(System.PullRequest.PullRequestNumber)
    TARGET_BRANCH: $[replace(variables['System.PullRequest.TargetBranch'],'refs/heads/','origin/')]
    BASE_SHA: $(git merge-base $(TARGET_BRANCH) HEAD)
  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(Build.SourceBranchName)
    BASE_SHA: $(git rev-parse HEAD~1)
  HEAD_SHA: $(git rev-parse HEAD)

jobs:
  - job: main
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: npm ci

      - script: npx nx format:check

      - script: npx nx affected --base=$(BASE_SHA) -t lint --parallel=3
      - script: npx nx affected --base=$(BASE_SHA) -t test --parallel=3 --configuration=ci
      - script: npx nx affected --base=$(BASE_SHA) -t build --parallel=3
```

But, I get an error when it runs `npx nx format:check`

> fatal: ambiguous argument 'master': unknown revision or path not in the working tree.

Using a suggestion in another comment (changing it from **check** to **write**), I get the same error in the logs, but it doesn't return an exit code of 1 and allows my pipeline to continue on to the next build task.

**Full build logs**

with `npx nx format:check`
```
Starting: CmdLine
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.212.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
npx nx format:check
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/38edf7c3-b384-4c31-bdc1-dee7fbdc928f.sh
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
apps/api-e2e/jest.config.ts
apps/api-e2e/src/api/api.spec.ts
apps/api-e2e/src/support/global-setup.ts
apps/api-e2e/src/support/test-setup.ts
apps/api/jest.config.ts
apps/api/src/app/app.controller.spec.ts
apps/api/src/app/app.controller.ts
apps/api/src/app/app.module.ts
apps/api/src/app/app.service.spec.ts
apps/api/src/app/app.service.ts
apps/api/src/main.ts
apps/api/webpack.config.js
apps/app/src/app/app.component.ts
jest.config.ts
jest.preset.js
##[error]Bash exited with code '1'.
Finishing: CmdLine
```

with `npx nx format:write`
```
Starting: CmdLine
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.212.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
npx nx format:write
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/27daa746-95fc-41d1-9993-5b0509e5e408.sh
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
apps/api-e2e/jest.config.ts
apps/api-e2e/src/api/api.spec.ts
apps/api-e2e/src/support/global-setup.ts
apps/api-e2e/src/support/test-setup.ts
apps/api/jest.config.ts
apps/api/src/app/app.controller.spec.ts
apps/api/src/app/app.controller.ts
apps/api/src/app/app.module.ts
apps/api/src/app/app.service.spec.ts
apps/api/src/app/app.service.ts
apps/api/src/main.ts
apps/api/webpack.config.js
apps/app/src/app/app.component.ts
jest.config.ts
jest.preset.js
tsconfig.base.json
Finishing: CmdLine
```

I created a documentation issue (#16241) for this initially, but it sounds like this command may be having troubles in a pipeline?

**Comment by ak274** [comment]
I'm also facing this issue in gitlab ci `npx nx format:check` fails without telling what's wrong! Wasted many hours and then come here to look into this issue

**Comment by tomavic** [comment]
I had same issue too and it's really confusing. Is it `main` or `master` :/

My `ci.yml`

```YAML
name: Publish Libraries
'on':
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo ✅
        uses: actions/checkout@v2
      - name: Install Dependencies 🔧
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - name: Pretty code 💄
        run: npx nx format:check
      - name: Lint ♻️
        run: npx nx affected -t lint
      - name: Build 📦
        run: npx nx affected -t build
      - name: Test 🧪
        run: npx nx affected -t test --ci --code-coverage
      - name: Release 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx nx affected -t release

```

and it fails at the linting stage, saying

```shell
Run npx nx affected -t lint
  npx nx affected -t lint
  shell: /usr/bin/bash -e {0}

 >  NX   Affected criteria defaulted to --base=master --head=HEAD

fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
nx affected

Run target for affected projects

Run command using --base=[SHA1] (affected by the committed, uncommitted and untracked changes):
      --base  Base of the current branch (usually main)  [string]

or using --base=[SHA1] --head=[SHA[2](https://github.com/tomavic/enigma-nx-angular/actions/runs/4710392822/jobs/8353993527?pr=2#step:5:2)] (affected by the committed changes):
      --base  Base of the current branch (usually main)  [string]
      --head  Latest commit of the current branch (usually HEAD)  [string]
```
