### ISSUE TITLE
Nextjs build caching

### ISSUE THREAD

**Issue by cyrus-za** [nrwl/nx#5221]
I am using github actions to buil my nx projects (to test builds)

I get this message 
```sh
warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: err.sh/next.js/no-cache
```

How do we configure this with nx in mind? `@nrwl/next` does not output to .next right? It outputs to dist/apps/** or am I wrong?

I added dist/apps as a caching layer but I still get the error. Probably because nextjs still looks for the cache in .next

**Comment by kirjai** [comment]
hey @cyrus-za !
so I haven't tried this myself in github actions yet, but we actually do have a `.next` directory, it's just inside `dist/apps/your-app-name`. 

So looking at Next's suggestion for github actions [here](https://nextjs.org/docs/messages/no-cache#github-actions), you should be able to point it to `dist/apps/your-app-name/.next/cache`. maybe give that a try and report back how it goes?

**Comment by cyrus-za** [comment]
seems like it was a hidden directory. needed to use `ls -a` to see it. Thanks.

**Comment by cyrus-za** [comment]
I tried adding cache, but still no luck

```yml
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            **/.cache
            **/dist/apps/**/.next/cache
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
```
