### ISSUE TITLE
Unable to run `yarn format:check` in CI Job

### ISSUE THREAD

**Issue by CWSites** [nrwl/nx#5611]
## Current Behavior
When running `yarn format:check` in my CI Job I get the following error

```
Run yarn format:check
yarn run v1.22.10
$ nx format:check

>  NX   NOTE  Affected criteria defaulted to --base=master --head=HEAD

fatal: Not a valid object name master
fatal: No such ref: 'master'
CI_CHANGE_LOG.md
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

## Expected Behavior
It started happening when I used my CI Job to create a file `CI_CHANGE_LOG.md` and commit it back to the master branch.

## Steps to Reproduce
This is my config for the CI Job

```yml
name: PR Deployment

on:
  pull_request:

jobs:
  verification:
    name: Lint, Format & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - run: |
          git fetch --no-tags --prune --depth=5 origin master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # https://github.com/marketplace/actions/yarn-install-cache
      - name: Cache yarn dependencies
        uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        run: yarn install

      - name: Lint Code
        run: yarn lint

      - name: Code Format Check
        run: yarn format:check
```

### Environment

```

  Node : 15.11.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.6.1
  @nrwl/cypress : 11.6.1
  @nrwl/devkit : 11.6.1
  @nrwl/eslint-plugin-nx : 11.6.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.1
  @nrwl/linter : 11.6.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.6.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.1
  @nrwl/web : 11.6.1
  @nrwl/workspace : 11.6.1
  @nrwl/storybook : 11.6.1
  @nrwl/gatsby : Not Found
  typescript : 4.0.7
  ```
