### ISSUE TITLE
Improve git clone performance in CI/CD environment

### ISSUE THREAD

**Issue by ild0tt0re** [nrwl/nx#5914]
## Description
I would like to leverage `nx affected` command to clone from a repository (`git clone`) only the files strictly needed for **CI/CD** operations.

## Motivation
A monorepo, per definition, increases its size continuously adding new projects, configs, tools, etc...
Large projects become soon a reality, so we can take advantage of `nx affected` capability also for **VCS**

## Suggested Implementation
`nx affected` specific use case for CI environment where we can use affected state saved from the previous run to download with `git clone` only the part of workspace tree needed for tasks
**See git partial clone:**
https://git-scm.com/docs/partial-clone

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

You can use the capabilities of your CI system to clone only a fragment of the history. For instance, you could do something like thins using GitHub actions. This can drastically reduce the size of the cloned repo.

```
   - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 10
```
