### ISSUE TITLE
Load .env on nx affected commands

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#7561]
## Description
I want to load a .env file when run `nx affected` commands

## Motivation
I'm using GitLab so I made a custom script, which essentially calls the gitlab api to find the last successful pipeline, in a similar way that `nx-set-shas` Github Action does, and then create a .env file with the proper `NX_BASE` and `NX_HEAD`, for now, I'm loading that file with a bash command but I think is better if nx is responsible of that

I have something like this

```
# .gitlab-ci.yml
main:
  image: node:16.13.0-alpine
  script:
    - apk add --no-cache git
    - npm i
    - npx nx-cloud start-ci-run
    - node ./tools/scripts/find-successful-pipeline.js $CI_JOB_TOKEN $CI_DEFAULT_BRANCH $CI_PROJECT_ID
    # ⬇️ This loads the variables
    - set -a
      [ -f .env ] && . .env
      set +a
    - npx nx affected --target=build --parallel --max-parallel=3
  after_script:
    - npx nx-cloud stop-all-agents
```

## Suggested Implementation
The feature maybe can be optional with a `--load-dotenv` flag to maintain the current behavior
