### ISSUE TITLE
Jest & lint fails with the following ERROR: NX   ERROR  spawn E2BIG

### ISSUE THREAD

**Issue by dean-g** [nrwl/nx#8646]
Both my jest & lint fails with the following ERROR: NX   ERROR  spawn E2BIG

this is happening only on the CI pipeline. but the same works well in my local machine. 

```
$ yarn affected:test 

yarn run v1.22.5
$ ./node_modules/.bin/nx affected:test --base=origin/test-code --parallel --detectOpenHandles --forceExit
>  NX   ERROR  spawn E2BIG
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

**Comment by Jeffrey-Zutt** [comment]
## Current Behavior
We are running into the same issue after updating from `13.4.5` to `13.4.6`.
Locally everything works just fine, but on our CI pipelines (gitlab) we're getting the following error:

```
$ npx nx affected:lint --base=origin/master
>  NX   ERROR  spawn E2BIG
```

## Expected Behavior

No E2BIG errors on `affected` commands.

## Steps to Reproduce

- Upgrade from `13.4.5` to `13.4.6`. 
- Run a `affected` command in a gitlab pipeline.

I will try to make a clean repository which reproduces this issue.

### Failure Logs
`>  NX   ERROR  spawn E2BIG`

### Environment
  NX  Report complete - copy this into the issue template
  Node : 16.13.2
  OS   : linux x64
  yarn : 1.22.15
  
  nx : 13.4.6
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.6
  @nrwl/cypress : 13.4.6
  @nrwl/devkit : 13.4.6
  @nrwl/eslint-plugin-nx : 13.4.6
  @nrwl/express : 13.4.6
  @nrwl/jest : 13.4.6
  @nrwl/linter : 13.4.6
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.4.6
  @nrwl/nx-cloud : 12.5.4
  @nrwl/react : 13.4.6
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.6
  @nrwl/web : 13.4.6
  @nrwl/workspace : 13.4.6
  @nrwl/storybook : 13.4.6
  @nrwl/gatsby : undefined
  typescript : 4.5.5
  rxjs : 6.6.7

**Comment by Jeffrey-Zutt** [comment]
OK.  After some debugging I was able to resolve the issue in our repo.
I'll try to explain the solution, hopefully its useful for others as well.

Also: Thank you for building NX! It's an awesome tool and we love using it.

# Our setup:

## 1. We specify cypress cache folder:
```
variables:
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'
```

## 2. We specify a cache object:
```
.cache_deps: &cache_deps
  key:
    files:
      - yarn.lock
  paths:
    - cache/Cypress
    - node_modules
```

## 3. We have an 'install' job.
```
install:
  image: node:lts-slim
  cache:
    <<: *cache_deps
    policy: push
  script:
    - yarn install --frozen-lockfile
```

_Note: cypress cache-folder amounts to almost 26.000 (!) files._

## 4. We have a 'lint' job.
```
lint:
  image: node:lts
  cache:
    <<: *cache_deps
    policy: pull
  script:
    - npx nx affected:lint --base=origin/master
```

Result:
```
$ npx nx affected:lint --base=origin/master
>  NX   ERROR  spawn E2BIG
```

# The solution:

Cypress cache is adding ~26.000 files which all are checked in the `affected`  command.
In our case, adding `/cache` (our custom cypress cache location) to `.gitignore` notifies NX to ignore all of these files. 

The `affected:lint` command to now run smoothly again for us.
