### ISSUE TITLE
NX Cloud seems to be incorrectly restoring from cache

### ISSUE THREAD

**Issue by jredl-va** [nrwl/nx#8828]
## Current Behavior
We are seeing nx and nx cloud restoring from cache incorrectly during nx build. 

## Expected Behavior
What should be triggering a new build is restoring from cache and new changes are not being included. This seems to be a regression in new versions of nx and nx cloud (I haven't been able to pin point when this was introduced). 

## Steps to Reproduce

The git commits to pass to nx are determined by the environment variable $COMMIT_SHA which is an environment variable for the current commit being built (google cloud build).

```
        # write the git revisions for the nx affected git comparison
        echo $COMMIT_SHA > HEAD
        echo $(git rev-parse $COMMIT_SHA~1) > BASE
```

Note, that we have had several reports of team members encountering this same issue (with different commits of course). 

The change that I build this morning was a simple one line change. This is a git hub diff of the same commits that were used for the nx build.
![image](https://user-images.githubusercontent.com/2300103/152379252-333fecf3-b301-4d8a-b07a-4b17472adbda.png)

```
npx nx affected:build --base=2d21bb4f635c7c7cda098996416a5ad838629a1f --head=6449eccf47322168812232b5a5e2547ca40636e1 --with-deps --prod --parallel
```

NX restored from cache incorrectly, as the above changes were not included in the cache restore:
![image](https://user-images.githubusercontent.com/2300103/152379836-d9ec42aa-6557-41e5-bc29-60526d989539.png)

### Environment
```
   Node : 14.18.3
   OS   : darwin x64
   npm  : 6.14.15

   nx : undefined
   @nrwl/angular : 13.7.1
   @nrwl/cli : 13.7.1
   @nrwl/cypress : 13.7.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.7.1
   @nrwl/eslint-plugin-nx : 13.7.1
   @nrwl/express : undefined
   @nrwl/jest : 13.7.1
   @nrwl/js : undefined
   @nrwl/linter : 13.7.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.2
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : 8.12.11
   @nrwl/storybook : 13.7.1
   @nrwl/tao : 13.7.1
   @nrwl/web : undefined
   @nrwl/workspace : 13.7.1
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
   	 @angular-devkit/architect: 0.1302.0
   	 @angular/animations: 13.2.0
   	 @angular/cdk: 13.2.0
   	 @angular/common: 13.2.0
   	 @angular/compiler: 13.2.0
   	 @angular/core: 13.2.0
   	 @angular/elements: 13.2.0
   	 @angular/fire: 6.1.4
   	 @angular/forms: 13.2.0
   	 @angular/localize: 13.2.0
   	 @angular/material: 13.2.0
   	 @angular/material-moment-adapter: 13.2.0
   	 @angular/platform-browser: 13.2.0
   	 @angular/platform-browser-dynamic: 13.2.0
   	 @angular/router: 13.2.0
   	 @angular/service-worker: 13.2.0
   	 @ngrx/effects: 13.0.1
   	 @ngrx/store: 13.0.1
   	 @ngrx/store-devtools: 13.0.1
   	 angular-calendar: 0.28.26
   	 ngx-bootstrap: 6.2.0
   	 @angular-builders/custom-webpack: 13.0.0
   	 @angular-devkit/build-angular: 13.2.0
   	 @angular/cli: 13.2.0
   	 @angular/compiler-cli: 13.2.0
   	 @angular/language-service: 13.2.0
   	 @ngneat/spectator: 6.1.3
   	 @testing-library/angular: 10.11.0
```

**Comment by timomeh** [comment]
I can confirm encountering the same issue.

**Comment by jredl-va** [comment]
Note, that by downgrading to `13.5.3` we are no longer encountering this issue.

**Comment by FrozenPandaz** [comment]
Sorry, could someone please provide a repo that I can use to reproduce the issue? I cannot seem to reproduce it here on the Nx repo.

**Comment by timomeh** [comment]
I can't provide a reproduction – as @jredl-va also said, it's very difficult to reproduce and demonstrate. But I can share some details, maybe something jumps out to you:

- The hash of an app was incorrectly calculated. Using the compare tool in Nx Cloud, I can see that the incorrectly restored build and the build it was restored from had the exact same hash for the app, although the code of this app changed between those builds.
- Both builds (the incorrectly restored build and the one which was restored from) both ran inside GCP CloudBuild, in a `docker build` job. It wasn't restored from a different environment.
- We also run a build inside GitHub Actions, as part of CI. It wasn't cached in GitHub Actions. In GitHub Actions, the change was correctly detected.
- GCP CloudBuild does a shallow clone of a commit. Inside the docker build step, the `.git` directory isn't available.
- In the Dockerfile, all files get `COPY`ed, except the contents of other apps. Only the project.json of other apps get copied. This is to leverage docker layer caching: the docker image for one app should stay cached if another app changes. Apps have no direct dependency between each other anyway.
- Even if this "partial clone" sounds fishy, the two builds ran in the same environment using the same steps. Both builds only differed in 1 file, which wasn't recognized as a change and thus produced the issue.

Looking at @jredl-va's Screenshot, it also looks like he's using CloudBuild... 🤔

Since this issue occurred, I disabled nx cache inside CloudBuild and haven't tried it since, although we're now at version 13.8.3. I didn't yet feel like testing it, the risk of this happening again and unintentionally shipping unchanged code (or worst case old code) is kinda high.

**Comment by TomONeill** [comment]
This might be totally unrelated, but may in some weird way point into the right direction?
Local:
1. Break your app intentionally by removing a method or something.
2. Run `nx build projectname`
3. Quickly after pressing `[enter]` in the previous step, fix the breaking change from step 1
Result: build succeeds and the current state of the code will be saved in cache, even though that state is a breaking state.

Seems rather easy to resolve by saving the state with build completion instead of before.

**Comment by jredl-va** [comment]
@timomeh We are indeed using cloud build (I feel I would like to reach out to you and understand how you are using docker for your caching but I will do that outside of this thread). 

The only difference is that we are unshallowing the repository before starting nx. For reference here are the build steps we are running within cloud build:


```
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'stop-ongoing-builds'
    args:
      - '-c'
      - |
        on_going_build=($(gcloud builds list --ongoing --format='value(id)' --filter="substitutions.TRIGGER_NAME=$TRIGGER_NAME AND substitutions.BRANCH_NAME=$BRANCH_NAME" | xargs))

        for (( i=0; i<${#on_going_build[@]}; i++ )); do
          if [ "$i" -gt "0" ]; then # skip current
            echo "Cancelling build ${on_going_build[i]}"

            gcloud builds cancel --no-user-output-enabled --verbosity=none ${on_going_build[i]}
          fi
        done
    entrypoint: bash
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/git'
    id: 'fetch'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # convert the shallow clone to regular one
        git fetch --unshallow --no-tags
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/git'
    id: 'write-version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # write the git revisions for the nx affected git comparison
        echo $COMMIT_SHA > HEAD
        echo $(git rev-parse origin/master) > BASE

        # write these revisions to the build log
        echo "nx head revision:" $(cat HEAD)
        echo "nx base revision:" $(cat BASE)
    waitFor: ['fetch']

  - name: 'node:16'
    id: 'npm-install'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm ci --unsafe-perm
    env:
      - 'CYPRESS_INSTALL_BINARY=0'
      - 'CYPRESS_CACHE_FOLDER=/cypress_cache'
    waitFor: ['fetch']


  - name: 'node:16'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npx nx affected:build --base=$(cat BASE) --head=$(cat HEAD) --prod --parallel=2
    waitFor: ['npm-install']
```
