### ISSUE TITLE
Dependent Packages Fail Silently and Build Hangs in Node 14

### ISSUE THREAD

**Issue by devonhumes** [nrwl/nx#9251]
## Current Behavior

When building packages with dependent packages, if one of the dependent packages fails (i.e. with a TypeScript compiler error) the build will hang with no error reporting. This makes it super hard to know which dependency failed.

The main issue appears to be an unhandled promise rejection for building the dependent package. 

```
(node:19636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

I tested this in Node 16 and it appears to work correctly.
## Expected Behavior

The builder should stop and an error should be reported.

## Steps to Reproduce

I've only tested this on a repo with packages instead of an application. Here is a repo with a reproduction branch. 

https://github.com/devonhumes/nx-sandbox/tree/build_fails_silently

Repro steps are:
1. Download Zip and unpack
2. `cd nx-sandbox-build_fails_silently`
3. `npm i`
4. `npm run build`

Result:

The build should hang with no output and will never complete. I've tested with the `--verbose` setting as well with the same outcome.

### Failure Logs

There are no logs in the CLI output. However, the correct error is given in `./node_modules/.cache/nx/terminalOutputs`. Here is an example file from my machine.

[cc169d82c1e8af32e03a49d0009806880f28f80e9058aa67674e16b68f4f9998.txt](https://github.com/nrwl/nx/files/8215714/cc169d82c1e8af32e03a49d0009806880f28f80e9058aa67674e16b68f4f9998.txt)

### Environment

   Node : 14.19.0
   OS   : darwin x64
   npm  : 8.5.2

   nx : 13.8.5
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.5
   @nrwl/cypress : undefined
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.5
   @nrwl/eslint-plugin-nx : 13.8.5
   @nrwl/express : undefined
   @nrwl/jest : 13.8.5
   @nrwl/js : 13.8.5
   @nrwl/linter : 13.8.5
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.8.5
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.5
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

**Comment by hcharley** [comment]
I believe I may be experiencing this as well.

Just as an aside:

In Github Actions, to grab those terminal outputs, I am doing this FYI:

```yaml
      - name: Cache nx
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules/.cache/nx
            !./node_modules/.cache/nx/terminalOutputs
          key: ${{ runner.os }}-nx-cache
          restore-keys: ${{ runner.os }}-nx-cache
```

```yaml
      - name: Archive nx logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: nx-logs
          path: ./node_modules/.cache/nx/terminalOutputs
          retention-days: 1
        timeout-minutes: 5
```
